// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    /// <summary>
    /// Configures the AI provider for a connector's session analyzer.
    /// </summary>
    [PulumiResourceType("formal:index/connectorAiProvider:ConnectorAiProvider")]
    public partial class ConnectorAiProvider : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Use Anthropic as the provider.
        /// </summary>
        [Output("anthropic")]
        public Output<Outputs.ConnectorAiProviderAnthropic?> Anthropic { get; private set; } = null!;

        /// <summary>
        /// Use AWS Bedrock as the provider.
        /// </summary>
        [Output("awsBedrock")]
        public Output<Outputs.ConnectorAiProviderAwsBedrock?> AwsBedrock { get; private set; } = null!;

        /// <summary>
        /// Use Azure AI Foundry as the provider.
        /// </summary>
        [Output("azureAi")]
        public Output<Outputs.ConnectorAiProviderAzureAi?> AzureAi { get; private set; } = null!;

        /// <summary>
        /// The ID of the connector this AI provider is linked to.
        /// </summary>
        [Output("connectorId")]
        public Output<string> ConnectorId { get; private set; } = null!;

        /// <summary>
        /// Use the Formal AI satellite as the provider.
        /// </summary>
        [Output("formalAiSatellite")]
        public Output<Outputs.ConnectorAiProviderFormalAiSatellite?> FormalAiSatellite { get; private set; } = null!;

        /// <summary>
        /// Use Google Gemini as the provider.
        /// </summary>
        [Output("gemini")]
        public Output<Outputs.ConnectorAiProviderGemini?> Gemini { get; private set; } = null!;

        /// <summary>
        /// Use Google Vertex AI as the provider.
        /// </summary>
        [Output("googleVertexAi")]
        public Output<Outputs.ConnectorAiProviderGoogleVertexAi?> GoogleVertexAi { get; private set; } = null!;

        /// <summary>
        /// Use OpenAI as the provider.
        /// </summary>
        [Output("openai")]
        public Output<Outputs.ConnectorAiProviderOpenai?> Openai { get; private set; } = null!;


        /// <summary>
        /// Create a ConnectorAiProvider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ConnectorAiProvider(string name, ConnectorAiProviderArgs args, CustomResourceOptions? options = null)
            : base("formal:index/connectorAiProvider:ConnectorAiProvider", name, args ?? new ConnectorAiProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ConnectorAiProvider(string name, Input<string> id, ConnectorAiProviderState? state = null, CustomResourceOptions? options = null)
            : base("formal:index/connectorAiProvider:ConnectorAiProvider", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/formalco",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ConnectorAiProvider resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ConnectorAiProvider Get(string name, Input<string> id, ConnectorAiProviderState? state = null, CustomResourceOptions? options = null)
        {
            return new ConnectorAiProvider(name, id, state, options);
        }
    }

    public sealed class ConnectorAiProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Use Anthropic as the provider.
        /// </summary>
        [Input("anthropic")]
        public Input<Inputs.ConnectorAiProviderAnthropicArgs>? Anthropic { get; set; }

        /// <summary>
        /// Use AWS Bedrock as the provider.
        /// </summary>
        [Input("awsBedrock")]
        public Input<Inputs.ConnectorAiProviderAwsBedrockArgs>? AwsBedrock { get; set; }

        /// <summary>
        /// Use Azure AI Foundry as the provider.
        /// </summary>
        [Input("azureAi")]
        public Input<Inputs.ConnectorAiProviderAzureAiArgs>? AzureAi { get; set; }

        /// <summary>
        /// The ID of the connector this AI provider is linked to.
        /// </summary>
        [Input("connectorId", required: true)]
        public Input<string> ConnectorId { get; set; } = null!;

        /// <summary>
        /// Use the Formal AI satellite as the provider.
        /// </summary>
        [Input("formalAiSatellite")]
        public Input<Inputs.ConnectorAiProviderFormalAiSatelliteArgs>? FormalAiSatellite { get; set; }

        /// <summary>
        /// Use Google Gemini as the provider.
        /// </summary>
        [Input("gemini")]
        public Input<Inputs.ConnectorAiProviderGeminiArgs>? Gemini { get; set; }

        /// <summary>
        /// Use Google Vertex AI as the provider.
        /// </summary>
        [Input("googleVertexAi")]
        public Input<Inputs.ConnectorAiProviderGoogleVertexAiArgs>? GoogleVertexAi { get; set; }

        /// <summary>
        /// Use OpenAI as the provider.
        /// </summary>
        [Input("openai")]
        public Input<Inputs.ConnectorAiProviderOpenaiArgs>? Openai { get; set; }

        public ConnectorAiProviderArgs()
        {
        }
        public static new ConnectorAiProviderArgs Empty => new ConnectorAiProviderArgs();
    }

    public sealed class ConnectorAiProviderState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Use Anthropic as the provider.
        /// </summary>
        [Input("anthropic")]
        public Input<Inputs.ConnectorAiProviderAnthropicGetArgs>? Anthropic { get; set; }

        /// <summary>
        /// Use AWS Bedrock as the provider.
        /// </summary>
        [Input("awsBedrock")]
        public Input<Inputs.ConnectorAiProviderAwsBedrockGetArgs>? AwsBedrock { get; set; }

        /// <summary>
        /// Use Azure AI Foundry as the provider.
        /// </summary>
        [Input("azureAi")]
        public Input<Inputs.ConnectorAiProviderAzureAiGetArgs>? AzureAi { get; set; }

        /// <summary>
        /// The ID of the connector this AI provider is linked to.
        /// </summary>
        [Input("connectorId")]
        public Input<string>? ConnectorId { get; set; }

        /// <summary>
        /// Use the Formal AI satellite as the provider.
        /// </summary>
        [Input("formalAiSatellite")]
        public Input<Inputs.ConnectorAiProviderFormalAiSatelliteGetArgs>? FormalAiSatellite { get; set; }

        /// <summary>
        /// Use Google Gemini as the provider.
        /// </summary>
        [Input("gemini")]
        public Input<Inputs.ConnectorAiProviderGeminiGetArgs>? Gemini { get; set; }

        /// <summary>
        /// Use Google Vertex AI as the provider.
        /// </summary>
        [Input("googleVertexAi")]
        public Input<Inputs.ConnectorAiProviderGoogleVertexAiGetArgs>? GoogleVertexAi { get; set; }

        /// <summary>
        /// Use OpenAI as the provider.
        /// </summary>
        [Input("openai")]
        public Input<Inputs.ConnectorAiProviderOpenaiGetArgs>? Openai { get; set; }

        public ConnectorAiProviderState()
        {
        }
        public static new ConnectorAiProviderState Empty => new ConnectorAiProviderState();
    }
}
