// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    /// <summary>
    /// Register a KMS key encryption key (KEK) for HTTP policy token encryption on a Connector.
    /// </summary>
    [PulumiResourceType("formal:index/connectorTokenEncryptionKey:ConnectorTokenEncryptionKey")]
    public partial class ConnectorTokenEncryptionKey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the Connector this token encryption key is linked to.
        /// </summary>
        [Output("connectorId")]
        public Output<string> ConnectorId { get; private set; } = null!;

        /// <summary>
        /// When the connector token encryption key was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Provider-native key identifier (AWS KMS ARN, GCP CryptoKey resource name, or Azure Key Vault key URI).
        /// </summary>
        [Output("keyId")]
        public Output<string> KeyId { get; private set; } = null!;

        /// <summary>
        /// The KMS provider. One of 'aws-kms', 'gcp-kms', or 'azure-key-vault'.
        /// </summary>
        [Output("keyProvider")]
        public Output<string> KeyProvider { get; private set; } = null!;

        /// <summary>
        /// Last update time.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a ConnectorTokenEncryptionKey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ConnectorTokenEncryptionKey(string name, ConnectorTokenEncryptionKeyArgs args, CustomResourceOptions? options = null)
            : base("formal:index/connectorTokenEncryptionKey:ConnectorTokenEncryptionKey", name, args ?? new ConnectorTokenEncryptionKeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ConnectorTokenEncryptionKey(string name, Input<string> id, ConnectorTokenEncryptionKeyState? state = null, CustomResourceOptions? options = null)
            : base("formal:index/connectorTokenEncryptionKey:ConnectorTokenEncryptionKey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/formalco",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ConnectorTokenEncryptionKey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ConnectorTokenEncryptionKey Get(string name, Input<string> id, ConnectorTokenEncryptionKeyState? state = null, CustomResourceOptions? options = null)
        {
            return new ConnectorTokenEncryptionKey(name, id, state, options);
        }
    }

    public sealed class ConnectorTokenEncryptionKeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Connector this token encryption key is linked to.
        /// </summary>
        [Input("connectorId", required: true)]
        public Input<string> ConnectorId { get; set; } = null!;

        /// <summary>
        /// Provider-native key identifier (AWS KMS ARN, GCP CryptoKey resource name, or Azure Key Vault key URI).
        /// </summary>
        [Input("keyId", required: true)]
        public Input<string> KeyId { get; set; } = null!;

        /// <summary>
        /// The KMS provider. One of 'aws-kms', 'gcp-kms', or 'azure-key-vault'.
        /// </summary>
        [Input("keyProvider", required: true)]
        public Input<string> KeyProvider { get; set; } = null!;

        public ConnectorTokenEncryptionKeyArgs()
        {
        }
        public static new ConnectorTokenEncryptionKeyArgs Empty => new ConnectorTokenEncryptionKeyArgs();
    }

    public sealed class ConnectorTokenEncryptionKeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the Connector this token encryption key is linked to.
        /// </summary>
        [Input("connectorId")]
        public Input<string>? ConnectorId { get; set; }

        /// <summary>
        /// When the connector token encryption key was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Provider-native key identifier (AWS KMS ARN, GCP CryptoKey resource name, or Azure Key Vault key URI).
        /// </summary>
        [Input("keyId")]
        public Input<string>? KeyId { get; set; }

        /// <summary>
        /// The KMS provider. One of 'aws-kms', 'gcp-kms', or 'azure-key-vault'.
        /// </summary>
        [Input("keyProvider")]
        public Input<string>? KeyProvider { get; set; }

        /// <summary>
        /// Last update time.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public ConnectorTokenEncryptionKeyState()
        {
        }
        public static new ConnectorTokenEncryptionKeyState Empty => new ConnectorTokenEncryptionKeyState();
    }
}
