// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    public static class GetGroups
    {
        /// <summary>
        /// Data source for listing all Groups in Formal.
        /// </summary>
        public static Task<GetGroupsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetGroupsResult>("formal:index/getGroups:getGroups", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Data source for listing all Groups in Formal.
        /// </summary>
        public static Output<GetGroupsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetGroupsResult>("formal:index/getGroups:getGroups", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Data source for listing all Groups in Formal.
        /// </summary>
        public static Output<GetGroupsResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetGroupsResult>("formal:index/getGroups:getGroups", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetGroupsResult
    {
        /// <summary>
        /// All Groups in Formal.
        /// </summary>
        public readonly ImmutableArray<Outputs.GetGroupsGroupResult> Groups;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetGroupsResult(
            ImmutableArray<Outputs.GetGroupsGroupResult> groups,

            string id)
        {
            Groups = groups;
            Id = id;
        }
    }
}
