// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    public static class GetSpace
    {
        /// <summary>
        /// Data source for looking up a Space by ID or by name. Use either `id` or `name`, but not both.
        /// </summary>
        public static Task<GetSpaceResult> InvokeAsync(GetSpaceArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSpaceResult>("formal:index/getSpace:getSpace", args ?? new GetSpaceArgs(), options.WithDefaults());

        /// <summary>
        /// Data source for looking up a Space by ID or by name. Use either `id` or `name`, but not both.
        /// </summary>
        public static Output<GetSpaceResult> Invoke(GetSpaceInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSpaceResult>("formal:index/getSpace:getSpace", args ?? new GetSpaceInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Data source for looking up a Space by ID or by name. Use either `id` or `name`, but not both.
        /// </summary>
        public static Output<GetSpaceResult> Invoke(GetSpaceInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSpaceResult>("formal:index/getSpace:getSpace", args ?? new GetSpaceInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSpaceArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Formal ID for this Space.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The name of the Space to look up. Use this to fetch a space by name.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetSpaceArgs()
        {
        }
        public static new GetSpaceArgs Empty => new GetSpaceArgs();
    }

    public sealed class GetSpaceInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The Formal ID for this Space.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// The name of the Space to look up. Use this to fetch a space by name.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetSpaceInvokeArgs()
        {
        }
        public static new GetSpaceInvokeArgs Empty => new GetSpaceInvokeArgs();
    }


    [OutputType]
    public sealed class GetSpaceResult
    {
        /// <summary>
        /// Creation time of the Space.
        /// </summary>
        public readonly int CreatedAt;
        /// <summary>
        /// Description of the Space.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The Formal ID for this Space.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The name of the Space to look up. Use this to fetch a space by name.
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// If set to true, this Space cannot be deleted.
        /// </summary>
        public readonly bool TerminationProtection;

        [OutputConstructor]
        private GetSpaceResult(
            int createdAt,

            string description,

            string? id,

            string? name,

            bool terminationProtection)
        {
            CreatedAt = createdAt;
            Description = description;
            Id = id;
            Name = name;
            TerminationProtection = terminationProtection;
        }
    }
}
