// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    /// <summary>
    /// Hooks are JavaScript functions evaluated during policy decisions. Policies reference hooks as `input.hooks.&lt;name&gt;`.
    /// </summary>
    [PulumiResourceType("formal:index/hook:Hook")]
    public partial class Hook : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Names of process environment variables the hook may read via its second `Env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `Env`.
        /// </summary>
        [Output("allowlistedEnvironmentVariables")]
        public Output<ImmutableArray<string>> AllowlistedEnvironmentVariables { get; private set; } = null!;

        /// <summary>
        /// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
        /// </summary>
        [Output("allowlistedNetworkHosts")]
        public Output<ImmutableArray<string>> AllowlistedNetworkHosts { get; private set; } = null!;

        /// <summary>
        /// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
        /// </summary>
        [Output("code")]
        public Output<string> Code { get; private set; } = null!;

        /// <summary>
        /// When the hook was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The hook description.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.&lt;name&gt;`.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The hook status. Accepted values are `Active` and `Draft`. Only active hooks can be referenced by policies.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;

        /// <summary>
        /// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
        /// </summary>
        [Output("timeoutMs")]
        public Output<int?> TimeoutMs { get; private set; } = null!;

        /// <summary>
        /// When the hook was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a Hook resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Hook(string name, HookArgs args, CustomResourceOptions? options = null)
            : base("formal:index/hook:Hook", name, args ?? new HookArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Hook(string name, Input<string> id, HookState? state = null, CustomResourceOptions? options = null)
            : base("formal:index/hook:Hook", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/formalco",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Hook resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Hook Get(string name, Input<string> id, HookState? state = null, CustomResourceOptions? options = null)
        {
            return new Hook(name, id, state, options);
        }
    }

    public sealed class HookArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowlistedEnvironmentVariables")]
        private InputList<string>? _allowlistedEnvironmentVariables;

        /// <summary>
        /// Names of process environment variables the hook may read via its second `Env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `Env`.
        /// </summary>
        public InputList<string> AllowlistedEnvironmentVariables
        {
            get => _allowlistedEnvironmentVariables ?? (_allowlistedEnvironmentVariables = new InputList<string>());
            set => _allowlistedEnvironmentVariables = value;
        }

        [Input("allowlistedNetworkHosts")]
        private InputList<string>? _allowlistedNetworkHosts;

        /// <summary>
        /// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
        /// </summary>
        public InputList<string> AllowlistedNetworkHosts
        {
            get => _allowlistedNetworkHosts ?? (_allowlistedNetworkHosts = new InputList<string>());
            set => _allowlistedNetworkHosts = value;
        }

        /// <summary>
        /// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
        /// </summary>
        [Input("code", required: true)]
        public Input<string> Code { get; set; } = null!;

        /// <summary>
        /// The hook description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.&lt;name&gt;`.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The hook status. Accepted values are `Active` and `Draft`. Only active hooks can be referenced by policies.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
        /// </summary>
        [Input("timeoutMs")]
        public Input<int>? TimeoutMs { get; set; }

        public HookArgs()
        {
        }
        public static new HookArgs Empty => new HookArgs();
    }

    public sealed class HookState : global::Pulumi.ResourceArgs
    {
        [Input("allowlistedEnvironmentVariables")]
        private InputList<string>? _allowlistedEnvironmentVariables;

        /// <summary>
        /// Names of process environment variables the hook may read via its second `Env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `Env`.
        /// </summary>
        public InputList<string> AllowlistedEnvironmentVariables
        {
            get => _allowlistedEnvironmentVariables ?? (_allowlistedEnvironmentVariables = new InputList<string>());
            set => _allowlistedEnvironmentVariables = value;
        }

        [Input("allowlistedNetworkHosts")]
        private InputList<string>? _allowlistedNetworkHosts;

        /// <summary>
        /// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
        /// </summary>
        public InputList<string> AllowlistedNetworkHosts
        {
            get => _allowlistedNetworkHosts ?? (_allowlistedNetworkHosts = new InputList<string>());
            set => _allowlistedNetworkHosts = value;
        }

        /// <summary>
        /// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
        /// </summary>
        [Input("code")]
        public Input<string>? Code { get; set; }

        /// <summary>
        /// When the hook was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// The hook description.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.&lt;name&gt;`.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The hook status. Accepted values are `Active` and `Draft`. Only active hooks can be referenced by policies.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
        /// </summary>
        [Input("timeoutMs")]
        public Input<int>? TimeoutMs { get; set; }

        /// <summary>
        /// When the hook was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public HookState()
        {
        }
        public static new HookState Empty => new HookState();
    }
}
