// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    /// <summary>
    /// Reports the Azure tenant and managed identity client id back to Formal to activate an Azure Cloud Integration.
    /// </summary>
    [PulumiResourceType("formal:index/integrationCloudAzureActivation:IntegrationCloudAzureActivation")]
    public partial class IntegrationCloudAzureActivation : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The client id of the managed identity created for this integration.
        /// </summary>
        [Output("clientId")]
        public Output<string> ClientId { get; private set; } = null!;

        /// <summary>
        /// The ID of the Azure Cloud Integration to activate.
        /// </summary>
        [Output("integrationId")]
        public Output<string> IntegrationId { get; private set; } = null!;

        /// <summary>
        /// The Entra tenant the managed identity created for this integration belongs to.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;


        /// <summary>
        /// Create a IntegrationCloudAzureActivation resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IntegrationCloudAzureActivation(string name, IntegrationCloudAzureActivationArgs args, CustomResourceOptions? options = null)
            : base("formal:index/integrationCloudAzureActivation:IntegrationCloudAzureActivation", name, args ?? new IntegrationCloudAzureActivationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IntegrationCloudAzureActivation(string name, Input<string> id, IntegrationCloudAzureActivationState? state = null, CustomResourceOptions? options = null)
            : base("formal:index/integrationCloudAzureActivation:IntegrationCloudAzureActivation", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/formalco",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IntegrationCloudAzureActivation resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IntegrationCloudAzureActivation Get(string name, Input<string> id, IntegrationCloudAzureActivationState? state = null, CustomResourceOptions? options = null)
        {
            return new IntegrationCloudAzureActivation(name, id, state, options);
        }
    }

    public sealed class IntegrationCloudAzureActivationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The client id of the managed identity created for this integration.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// The ID of the Azure Cloud Integration to activate.
        /// </summary>
        [Input("integrationId", required: true)]
        public Input<string> IntegrationId { get; set; } = null!;

        /// <summary>
        /// The Entra tenant the managed identity created for this integration belongs to.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public IntegrationCloudAzureActivationArgs()
        {
        }
        public static new IntegrationCloudAzureActivationArgs Empty => new IntegrationCloudAzureActivationArgs();
    }

    public sealed class IntegrationCloudAzureActivationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The client id of the managed identity created for this integration.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// The ID of the Azure Cloud Integration to activate.
        /// </summary>
        [Input("integrationId")]
        public Input<string>? IntegrationId { get; set; }

        /// <summary>
        /// The Entra tenant the managed identity created for this integration belongs to.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        public IntegrationCloudAzureActivationState()
        {
        }
        public static new IntegrationCloudAzureActivationState Empty => new IntegrationCloudAzureActivationState();
    }
}
