// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Formal
{
    /// <summary>
    /// Registering a Integration MFA app.
    /// </summary>
    [FormalResourceType("formal:index/integrationMfa:IntegrationMfa")]
    public partial class IntegrationMfa : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Configuration block for Duo integration. This block is optional and may be omitted if not configuring a Duo integration.
        /// </summary>
        [Output("duo")]
        public Output<Outputs.IntegrationMfaDuo?> Duo { get; private set; } = null!;

        /// <summary>
        /// Name of the Integration
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// If set to true, this Integration MFA cannot be deleted.
        /// </summary>
        [Output("terminationProtection")]
        public Output<bool?> TerminationProtection { get; private set; } = null!;


        /// <summary>
        /// Create a IntegrationMfa resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IntegrationMfa(string name, IntegrationMfaArgs? args = null, CustomResourceOptions? options = null)
            : base("formal:index/integrationMfa:IntegrationMfa", name, args ?? new IntegrationMfaArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IntegrationMfa(string name, Input<string> id, IntegrationMfaState? state = null, CustomResourceOptions? options = null)
            : base("formal:index/integrationMfa:IntegrationMfa", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/formalco",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IntegrationMfa resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IntegrationMfa Get(string name, Input<string> id, IntegrationMfaState? state = null, CustomResourceOptions? options = null)
        {
            return new IntegrationMfa(name, id, state, options);
        }
    }

    public sealed class IntegrationMfaArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration block for Duo integration. This block is optional and may be omitted if not configuring a Duo integration.
        /// </summary>
        [Input("duo")]
        public Input<Inputs.IntegrationMfaDuoArgs>? Duo { get; set; }

        /// <summary>
        /// Name of the Integration
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// If set to true, this Integration MFA cannot be deleted.
        /// </summary>
        [Input("terminationProtection")]
        public Input<bool>? TerminationProtection { get; set; }

        public IntegrationMfaArgs()
        {
        }
        public static new IntegrationMfaArgs Empty => new IntegrationMfaArgs();
    }

    public sealed class IntegrationMfaState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Configuration block for Duo integration. This block is optional and may be omitted if not configuring a Duo integration.
        /// </summary>
        [Input("duo")]
        public Input<Inputs.IntegrationMfaDuoGetArgs>? Duo { get; set; }

        /// <summary>
        /// Name of the Integration
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// If set to true, this Integration MFA cannot be deleted.
        /// </summary>
        [Input("terminationProtection")]
        public Input<bool>? TerminationProtection { get; set; }

        public IntegrationMfaState()
        {
        }
        public static new IntegrationMfaState Empty => new IntegrationMfaState();
    }
}
