// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    /// <summary>
    /// Registers an OIDC trust configuration used to authenticate externally signed JWTs to the Formal control plane as a machine user.
    /// </summary>
    [PulumiResourceType("formal:index/integrationOidc:IntegrationOidc")]
    public partial class IntegrationOidc : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The Formal audience value that tokens may present: `oidc.formal.ai/{id}`. Providers that cannot set a custom audience (e.g. Spacelift) can instead send `X-Formal-OIDC-Integration-Id` with this resource's `Id`.
        /// </summary>
        [Output("audience")]
        public Output<string> Audience { get; private set; } = null!;

        /// <summary>
        /// CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `True`. When selecting the integration with `X-Formal-OIDC-Integration-Id`, this condition must validate the provider-native audience and identity claims.
        /// </summary>
        [Output("claimCondition")]
        public Output<string?> ClaimCondition { get; private set; } = null!;

        /// <summary>
        /// When the integration was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        /// </summary>
        [Output("endUserEmailExpression")]
        public Output<string?> EndUserEmailExpression { get; private set; } = null!;

        /// <summary>
        /// OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        /// </summary>
        [Output("issuer")]
        public Output<string> Issuer { get; private set; } = null!;

        /// <summary>
        /// Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        /// </summary>
        [Output("jwksUri")]
        public Output<string?> JwksUri { get; private set; } = null!;

        /// <summary>
        /// ID of the Formal machine user that authenticated OIDC tokens map to.
        /// </summary>
        [Output("machineUserId")]
        public Output<string> MachineUserId { get; private set; } = null!;

        /// <summary>
        /// Friendly name for the OIDC integration. Must be unique within the organization.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Integration status. Accepted values are `Active` and `Draft`. Draft disables authentication.
        /// </summary>
        [Output("status")]
        public Output<string?> Status { get; private set; } = null!;

        /// <summary>
        /// When the integration was last updated.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a IntegrationOidc resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public IntegrationOidc(string name, IntegrationOidcArgs args, CustomResourceOptions? options = null)
            : base("formal:index/integrationOidc:IntegrationOidc", name, args ?? new IntegrationOidcArgs(), MakeResourceOptions(options, ""))
        {
        }

        private IntegrationOidc(string name, Input<string> id, IntegrationOidcState? state = null, CustomResourceOptions? options = null)
            : base("formal:index/integrationOidc:IntegrationOidc", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/formalco",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing IntegrationOidc resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static IntegrationOidc Get(string name, Input<string> id, IntegrationOidcState? state = null, CustomResourceOptions? options = null)
        {
            return new IntegrationOidc(name, id, state, options);
        }
    }

    public sealed class IntegrationOidcArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `True`. When selecting the integration with `X-Formal-OIDC-Integration-Id`, this condition must validate the provider-native audience and identity claims.
        /// </summary>
        [Input("claimCondition")]
        public Input<string>? ClaimCondition { get; set; }

        /// <summary>
        /// Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        /// </summary>
        [Input("endUserEmailExpression")]
        public Input<string>? EndUserEmailExpression { get; set; }

        /// <summary>
        /// OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        /// </summary>
        [Input("issuer", required: true)]
        public Input<string> Issuer { get; set; } = null!;

        /// <summary>
        /// Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        /// </summary>
        [Input("jwksUri")]
        public Input<string>? JwksUri { get; set; }

        /// <summary>
        /// ID of the Formal machine user that authenticated OIDC tokens map to.
        /// </summary>
        [Input("machineUserId", required: true)]
        public Input<string> MachineUserId { get; set; } = null!;

        /// <summary>
        /// Friendly name for the OIDC integration. Must be unique within the organization.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Integration status. Accepted values are `Active` and `Draft`. Draft disables authentication.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public IntegrationOidcArgs()
        {
        }
        public static new IntegrationOidcArgs Empty => new IntegrationOidcArgs();
    }

    public sealed class IntegrationOidcState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The Formal audience value that tokens may present: `oidc.formal.ai/{id}`. Providers that cannot set a custom audience (e.g. Spacelift) can instead send `X-Formal-OIDC-Integration-Id` with this resource's `Id`.
        /// </summary>
        [Input("audience")]
        public Input<string>? Audience { get; set; }

        /// <summary>
        /// CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `True`. When selecting the integration with `X-Formal-OIDC-Integration-Id`, this condition must validate the provider-native audience and identity claims.
        /// </summary>
        [Input("claimCondition")]
        public Input<string>? ClaimCondition { get; set; }

        /// <summary>
        /// When the integration was created.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        /// </summary>
        [Input("endUserEmailExpression")]
        public Input<string>? EndUserEmailExpression { get; set; }

        /// <summary>
        /// OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        /// </summary>
        [Input("issuer")]
        public Input<string>? Issuer { get; set; }

        /// <summary>
        /// Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        /// </summary>
        [Input("jwksUri")]
        public Input<string>? JwksUri { get; set; }

        /// <summary>
        /// ID of the Formal machine user that authenticated OIDC tokens map to.
        /// </summary>
        [Input("machineUserId")]
        public Input<string>? MachineUserId { get; set; }

        /// <summary>
        /// Friendly name for the OIDC integration. Must be unique within the organization.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Integration status. Accepted values are `Active` and `Draft`. Draft disables authentication.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        /// <summary>
        /// When the integration was last updated.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public IntegrationOidcState()
        {
        }
        public static new IntegrationOidcState Empty => new IntegrationOidcState();
    }
}
