// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi
{
    /// <summary>
    /// A Native User the Formal connector authenticates to a Resource as. The Resource decides which Native User a session uses through its `formal.ResourceNativeUserSelection` expression.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Pulumi = Formal.Pulumi;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var config = new Config();
    ///     var analyticsAdminPassword = config.Require("analyticsAdminPassword");
    ///     var db = new Pulumi.Resource("db", new()
    ///     {
    ///         Name = "analytics-postgres",
    ///         Hostname = "analytics.internal",
    ///         Technology = "postgres",
    ///         Port = 5432,
    ///         NativeUsersV3Enabled = true,
    ///     });
    /// 
    ///     // Username and password, read from an environment variable on the connector.
    ///     var basic = new Pulumi.NativeUserV3("basic", new()
    ///     {
    ///         Basic = new Pulumi.Inputs.NativeUserV3BasicArgs
    ///         {
    ///             Password = new Pulumi.Inputs.NativeUserV3BasicPasswordArgs
    ///             {
    ///                 EnvironmentVariable = "ANALYTICS_ADMIN_PASSWORD",
    ///             },
    ///             Username = "app_admin",
    ///         },
    ///         ResourceId = db.Id,
    ///         Label = "admin",
    ///     });
    /// 
    ///     // Username and password, with the password passed as a write-only value so it
    ///     // never lands in Terraform state. Increment literal_wo_version to rotate it.
    ///     var basicWriteOnly = new Pulumi.NativeUserV3("basic_write_only", new()
    ///     {
    ///         Basic = new Pulumi.Inputs.NativeUserV3BasicArgs
    ///         {
    ///             Password = new Pulumi.Inputs.NativeUserV3BasicPasswordArgs
    ///             {
    ///                 LiteralWo = analyticsAdminPassword,
    ///                 LiteralWoVersion = 1,
    ///             },
    ///             Username = "app_admin",
    ///         },
    ///         ResourceId = db.Id,
    ///         Label = "admin-write-only",
    ///     });
    /// 
    ///     // AWS IAM, inheriting the role from the connector's environment.
    ///     var awsIam = new Pulumi.NativeUserV3("aws_iam", new()
    ///     {
    ///         AwsIam = new Pulumi.Inputs.NativeUserV3AwsIamArgs
    ///         {
    ///             Username = "app_iam",
    ///         },
    ///         ResourceId = db.Id,
    ///         Label = "iam",
    ///     });
    /// 
    ///     var api = new Pulumi.Resource("api", new()
    ///     {
    ///         Name = "billing-api",
    ///         Hostname = "billing.internal",
    ///         Technology = "http",
    ///         Port = 443,
    ///         NativeUsersV3Enabled = true,
    ///     });
    /// 
    ///     var bearerToken = new Pulumi.NativeUserV3("bearer_token", new()
    ///     {
    ///         HttpBearer = new Pulumi.Inputs.NativeUserV3HttpBearerArgs
    ///         {
    ///             Token = new Pulumi.Inputs.NativeUserV3HttpBearerTokenArgs
    ///             {
    ///                 EnvironmentVariable = "BILLING_API_TOKEN",
    ///             },
    ///             Header = "Authorization",
    ///         },
    ///         ResourceId = api.Id,
    ///         Label = "service-account",
    ///     });
    /// 
    ///     // Credentials resolved at connection time by a hook running on the connector,
    ///     // for example to mint short-lived credentials from a secrets manager.
    ///     var fromHook = new Pulumi.NativeUserV3("from_hook", new()
    ///     {
    ///         Hook = new Pulumi.Inputs.NativeUserV3HookArgs
    ///         {
    ///             OutputType = "basic",
    ///             AllowlistedEnvVariables = new[]
    ///             {
    ///                 "FORMAL_ENV_USER",
    ///                 "FORMAL_ENV_PASSWORD",
    ///             },
    ///             Code = @"export default async function (_input, env) {
    ///   return {
    ///     username: env.FORMAL_ENV_USER,
    ///     password: env.FORMAL_ENV_PASSWORD,
    ///   };
    /// }
    /// ",
    ///         },
    ///         ResourceId = db.Id,
    ///         Label = "dynamic",
    ///     });
    /// 
    /// });
    /// ```
    /// </summary>
    [PulumiResourceType("formal:index/nativeUserV3:NativeUserV3")]
    public partial class NativeUserV3 : global::Pulumi.CustomResource
    {
        /// <summary>
        /// AWS IAM authentication.
        /// </summary>
        [Output("awsIam")]
        public Output<Outputs.NativeUserV3AwsIam?> AwsIam { get; private set; } = null!;

        /// <summary>
        /// AWS IAM authentication using an assumed role.
        /// </summary>
        [Output("awsIamRole")]
        public Output<Outputs.NativeUserV3AwsIamRole?> AwsIamRole { get; private set; } = null!;

        /// <summary>
        /// Azure IAM authentication.
        /// </summary>
        [Output("azureIam")]
        public Output<Outputs.NativeUserV3AzureIam?> AzureIam { get; private set; } = null!;

        /// <summary>
        /// Username and password authentication, for example Postgres or MySQL.
        /// </summary>
        [Output("basic")]
        public Output<Outputs.NativeUserV3Basic?> Basic { get; private set; } = null!;

        /// <summary>
        /// Creation time of the Native User.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// GCP IAM authentication.
        /// </summary>
        [Output("gcpIam")]
        public Output<Outputs.NativeUserV3GcpIam?> GcpIam { get; private set; } = null!;

        /// <summary>
        /// Credentials resolved on the connector by running a hook.
        /// </summary>
        [Output("hook")]
        public Output<Outputs.NativeUserV3Hook?> Hook { get; private set; } = null!;

        /// <summary>
        /// HTTP API key authentication, sent as a header.
        /// </summary>
        [Output("httpApiKeyHeader")]
        public Output<Outputs.NativeUserV3HttpApiKeyHeader?> HttpApiKeyHeader { get; private set; } = null!;

        /// <summary>
        /// HTTP API key authentication, sent as a query parameter.
        /// </summary>
        [Output("httpApiKeyQuery")]
        public Output<Outputs.NativeUserV3HttpApiKeyQuery?> HttpApiKeyQuery { get; private set; } = null!;

        /// <summary>
        /// HTTP Basic authentication, injected on a named header.
        /// </summary>
        [Output("httpBasic")]
        public Output<Outputs.NativeUserV3HttpBasic?> HttpBasic { get; private set; } = null!;

        /// <summary>
        /// HTTP Bearer token authentication, injected on a named header.
        /// </summary>
        [Output("httpBearer")]
        public Output<Outputs.NativeUserV3HttpBearer?> HttpBearer { get; private set; } = null!;

        /// <summary>
        /// Kubernetes authentication using an inline kubeconfig document.
        /// </summary>
        [Output("kubernetesInline")]
        public Output<Outputs.NativeUserV3KubernetesInline?> KubernetesInline { get; private set; } = null!;

        /// <summary>
        /// Kubernetes authentication using a kubeconfig file path on the connector.
        /// </summary>
        [Output("kubernetesPath")]
        public Output<Outputs.NativeUserV3KubernetesPath?> KubernetesPath { get; private set; } = null!;

        /// <summary>
        /// A name for this Native User, unique within the Resource. Selection expressions reference the Native User by ID, so the label is safe to rename.
        /// </summary>
        [Output("label")]
        public Output<string> Label { get; private set; } = null!;

        /// <summary>
        /// The ID of the Resource this Native User authenticates to.
        /// </summary>
        [Output("resourceId")]
        public Output<string> ResourceId { get; private set; } = null!;

        /// <summary>
        /// Snowflake key-pair authentication.
        /// </summary>
        [Output("snowflakeKey")]
        public Output<Outputs.NativeUserV3SnowflakeKey?> SnowflakeKey { get; private set; } = null!;

        /// <summary>
        /// SSH private key authentication.
        /// </summary>
        [Output("sshKey")]
        public Output<Outputs.NativeUserV3SshKey?> SshKey { get; private set; } = null!;

        /// <summary>
        /// If set to true, this Native User cannot be deleted.
        /// </summary>
        [Output("terminationProtection")]
        public Output<bool?> TerminationProtection { get; private set; } = null!;

        /// <summary>
        /// Last update time of the Native User.
        /// </summary>
        [Output("updatedAt")]
        public Output<string> UpdatedAt { get; private set; } = null!;


        /// <summary>
        /// Create a NativeUserV3 resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NativeUserV3(string name, NativeUserV3Args args, CustomResourceOptions? options = null)
            : base("formal:index/nativeUserV3:NativeUserV3", name, args ?? new NativeUserV3Args(), MakeResourceOptions(options, ""))
        {
        }

        private NativeUserV3(string name, Input<string> id, NativeUserV3State? state = null, CustomResourceOptions? options = null)
            : base("formal:index/nativeUserV3:NativeUserV3", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/formalco",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NativeUserV3 resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NativeUserV3 Get(string name, Input<string> id, NativeUserV3State? state = null, CustomResourceOptions? options = null)
        {
            return new NativeUserV3(name, id, state, options);
        }
    }

    public sealed class NativeUserV3Args : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// AWS IAM authentication.
        /// </summary>
        [Input("awsIam")]
        public Input<Inputs.NativeUserV3AwsIamArgs>? AwsIam { get; set; }

        /// <summary>
        /// AWS IAM authentication using an assumed role.
        /// </summary>
        [Input("awsIamRole")]
        public Input<Inputs.NativeUserV3AwsIamRoleArgs>? AwsIamRole { get; set; }

        /// <summary>
        /// Azure IAM authentication.
        /// </summary>
        [Input("azureIam")]
        public Input<Inputs.NativeUserV3AzureIamArgs>? AzureIam { get; set; }

        /// <summary>
        /// Username and password authentication, for example Postgres or MySQL.
        /// </summary>
        [Input("basic")]
        public Input<Inputs.NativeUserV3BasicArgs>? Basic { get; set; }

        /// <summary>
        /// GCP IAM authentication.
        /// </summary>
        [Input("gcpIam")]
        public Input<Inputs.NativeUserV3GcpIamArgs>? GcpIam { get; set; }

        /// <summary>
        /// Credentials resolved on the connector by running a hook.
        /// </summary>
        [Input("hook")]
        public Input<Inputs.NativeUserV3HookArgs>? Hook { get; set; }

        /// <summary>
        /// HTTP API key authentication, sent as a header.
        /// </summary>
        [Input("httpApiKeyHeader")]
        public Input<Inputs.NativeUserV3HttpApiKeyHeaderArgs>? HttpApiKeyHeader { get; set; }

        /// <summary>
        /// HTTP API key authentication, sent as a query parameter.
        /// </summary>
        [Input("httpApiKeyQuery")]
        public Input<Inputs.NativeUserV3HttpApiKeyQueryArgs>? HttpApiKeyQuery { get; set; }

        /// <summary>
        /// HTTP Basic authentication, injected on a named header.
        /// </summary>
        [Input("httpBasic")]
        public Input<Inputs.NativeUserV3HttpBasicArgs>? HttpBasic { get; set; }

        /// <summary>
        /// HTTP Bearer token authentication, injected on a named header.
        /// </summary>
        [Input("httpBearer")]
        public Input<Inputs.NativeUserV3HttpBearerArgs>? HttpBearer { get; set; }

        /// <summary>
        /// Kubernetes authentication using an inline kubeconfig document.
        /// </summary>
        [Input("kubernetesInline")]
        public Input<Inputs.NativeUserV3KubernetesInlineArgs>? KubernetesInline { get; set; }

        /// <summary>
        /// Kubernetes authentication using a kubeconfig file path on the connector.
        /// </summary>
        [Input("kubernetesPath")]
        public Input<Inputs.NativeUserV3KubernetesPathArgs>? KubernetesPath { get; set; }

        /// <summary>
        /// A name for this Native User, unique within the Resource. Selection expressions reference the Native User by ID, so the label is safe to rename.
        /// </summary>
        [Input("label", required: true)]
        public Input<string> Label { get; set; } = null!;

        /// <summary>
        /// The ID of the Resource this Native User authenticates to.
        /// </summary>
        [Input("resourceId", required: true)]
        public Input<string> ResourceId { get; set; } = null!;

        /// <summary>
        /// Snowflake key-pair authentication.
        /// </summary>
        [Input("snowflakeKey")]
        public Input<Inputs.NativeUserV3SnowflakeKeyArgs>? SnowflakeKey { get; set; }

        /// <summary>
        /// SSH private key authentication.
        /// </summary>
        [Input("sshKey")]
        public Input<Inputs.NativeUserV3SshKeyArgs>? SshKey { get; set; }

        /// <summary>
        /// If set to true, this Native User cannot be deleted.
        /// </summary>
        [Input("terminationProtection")]
        public Input<bool>? TerminationProtection { get; set; }

        public NativeUserV3Args()
        {
        }
        public static new NativeUserV3Args Empty => new NativeUserV3Args();
    }

    public sealed class NativeUserV3State : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// AWS IAM authentication.
        /// </summary>
        [Input("awsIam")]
        public Input<Inputs.NativeUserV3AwsIamGetArgs>? AwsIam { get; set; }

        /// <summary>
        /// AWS IAM authentication using an assumed role.
        /// </summary>
        [Input("awsIamRole")]
        public Input<Inputs.NativeUserV3AwsIamRoleGetArgs>? AwsIamRole { get; set; }

        /// <summary>
        /// Azure IAM authentication.
        /// </summary>
        [Input("azureIam")]
        public Input<Inputs.NativeUserV3AzureIamGetArgs>? AzureIam { get; set; }

        /// <summary>
        /// Username and password authentication, for example Postgres or MySQL.
        /// </summary>
        [Input("basic")]
        public Input<Inputs.NativeUserV3BasicGetArgs>? Basic { get; set; }

        /// <summary>
        /// Creation time of the Native User.
        /// </summary>
        [Input("createdAt")]
        public Input<string>? CreatedAt { get; set; }

        /// <summary>
        /// GCP IAM authentication.
        /// </summary>
        [Input("gcpIam")]
        public Input<Inputs.NativeUserV3GcpIamGetArgs>? GcpIam { get; set; }

        /// <summary>
        /// Credentials resolved on the connector by running a hook.
        /// </summary>
        [Input("hook")]
        public Input<Inputs.NativeUserV3HookGetArgs>? Hook { get; set; }

        /// <summary>
        /// HTTP API key authentication, sent as a header.
        /// </summary>
        [Input("httpApiKeyHeader")]
        public Input<Inputs.NativeUserV3HttpApiKeyHeaderGetArgs>? HttpApiKeyHeader { get; set; }

        /// <summary>
        /// HTTP API key authentication, sent as a query parameter.
        /// </summary>
        [Input("httpApiKeyQuery")]
        public Input<Inputs.NativeUserV3HttpApiKeyQueryGetArgs>? HttpApiKeyQuery { get; set; }

        /// <summary>
        /// HTTP Basic authentication, injected on a named header.
        /// </summary>
        [Input("httpBasic")]
        public Input<Inputs.NativeUserV3HttpBasicGetArgs>? HttpBasic { get; set; }

        /// <summary>
        /// HTTP Bearer token authentication, injected on a named header.
        /// </summary>
        [Input("httpBearer")]
        public Input<Inputs.NativeUserV3HttpBearerGetArgs>? HttpBearer { get; set; }

        /// <summary>
        /// Kubernetes authentication using an inline kubeconfig document.
        /// </summary>
        [Input("kubernetesInline")]
        public Input<Inputs.NativeUserV3KubernetesInlineGetArgs>? KubernetesInline { get; set; }

        /// <summary>
        /// Kubernetes authentication using a kubeconfig file path on the connector.
        /// </summary>
        [Input("kubernetesPath")]
        public Input<Inputs.NativeUserV3KubernetesPathGetArgs>? KubernetesPath { get; set; }

        /// <summary>
        /// A name for this Native User, unique within the Resource. Selection expressions reference the Native User by ID, so the label is safe to rename.
        /// </summary>
        [Input("label")]
        public Input<string>? Label { get; set; }

        /// <summary>
        /// The ID of the Resource this Native User authenticates to.
        /// </summary>
        [Input("resourceId")]
        public Input<string>? ResourceId { get; set; }

        /// <summary>
        /// Snowflake key-pair authentication.
        /// </summary>
        [Input("snowflakeKey")]
        public Input<Inputs.NativeUserV3SnowflakeKeyGetArgs>? SnowflakeKey { get; set; }

        /// <summary>
        /// SSH private key authentication.
        /// </summary>
        [Input("sshKey")]
        public Input<Inputs.NativeUserV3SshKeyGetArgs>? SshKey { get; set; }

        /// <summary>
        /// If set to true, this Native User cannot be deleted.
        /// </summary>
        [Input("terminationProtection")]
        public Input<bool>? TerminationProtection { get; set; }

        /// <summary>
        /// Last update time of the Native User.
        /// </summary>
        [Input("updatedAt")]
        public Input<string>? UpdatedAt { get; set; }

        public NativeUserV3State()
        {
        }
        public static new NativeUserV3State Empty => new NativeUserV3State();
    }
}
