// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class ConnectorAiProviderAzureAi
    {
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// The API key. This value is not stored in Terraform state.
        /// </summary>
        public readonly string ApiKey;
        /// <summary>
        /// Version trigger for `ApiKey`. Increment this value to update the key.
        /// </summary>
        public readonly int ApiKeyVersion;
        /// <summary>
        /// The Azure AI Foundry endpoint URL.
        /// </summary>
        public readonly string Endpoint;

        [OutputConstructor]
        private ConnectorAiProviderAzureAi(
            string apiKey,

            int apiKeyVersion,

            string endpoint)
        {
            ApiKey = apiKey;
            ApiKeyVersion = apiKeyVersion;
            Endpoint = endpoint;
        }
    }
}
