// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class FormField
    {
        /// <summary>
        /// Optional field configuration for select-like field types.
        /// </summary>
        public readonly Outputs.FormFieldConfig? Config;
        /// <summary>
        /// Unique field identifier.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Display name of the field.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Field type.
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private FormField(
            Outputs.FormFieldConfig? config,

            string id,

            string name,

            string type)
        {
            Config = config;
            Id = id;
            Name = name;
            Type = type;
        }
    }
}
