// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class GetGroupsGroupResult
    {
        /// <summary>
        /// Description for this Group.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The ID of the Group.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// The name of the Group.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// If set to true, this Group cannot be deleted.
        /// </summary>
        public readonly bool TerminationProtection;

        [OutputConstructor]
        private GetGroupsGroupResult(
            string description,

            string id,

            string name,

            bool terminationProtection)
        {
            Description = description;
            Id = id;
            Name = name;
            TerminationProtection = terminationProtection;
        }
    }
}
