// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class IntegrationMdmJamf
    {
        /// <summary>
        /// **NOTE:** This field is write-only and its value will not be updated in state as part of read operations.
        /// OAuth client secret for your Jamf Pro API client. This value is not stored in Terraform state. To rotate the secret, change this value and run `terraform apply -replace=&lt;resource address&gt;`.
        /// </summary>
        public readonly string ApiKey;
        /// <summary>
        /// API URL of your Jamf Pro instance.
        /// </summary>
        public readonly string ApiUrl;
        /// <summary>
        /// OAuth client ID for your Jamf Pro API client.
        /// </summary>
        public readonly string ClientId;

        [OutputConstructor]
        private IntegrationMdmJamf(
            string apiKey,

            string apiUrl,

            string clientId)
        {
            ApiKey = apiKey;
            ApiUrl = apiUrl;
            ClientId = clientId;
        }
    }
}
