// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class IntegrationCloudAws
    {
        /// <summary>
        /// Allows the Cloud Integration to access S3 buckets for Log Integrations.
        /// </summary>
        public readonly bool? AllowS3Access;
        /// <summary>
        /// The regions to enable resource autodiscovery for.
        /// </summary>
        public readonly ImmutableArray<string> AutodiscoveryRegions;
        /// <summary>
        /// The ARN of the IAM role that Formal assumes in your AWS account to access your resources. Required unless `TemplateVersion` is set (CloudFormation path).
        /// </summary>
        public readonly string? AwsCustomerRoleArn;
        /// <summary>
        /// Enables resource autodiscovery for EC2 instances.
        /// </summary>
        public readonly bool? EnableEc2Autodiscovery;
        /// <summary>
        /// Enables resource autodiscovery for ECS clusters.
        /// </summary>
        public readonly bool? EnableEcsAutodiscovery;
        /// <summary>
        /// Enables resource autodiscovery for EKS clusters.
        /// </summary>
        public readonly bool? EnableEksAutodiscovery;
        /// <summary>
        /// Enables resource autodiscovery for RDS instances (PostgreSQL, MySQL, MongoDB).
        /// </summary>
        public readonly bool? EnableRdsAutodiscovery;
        /// <summary>
        /// Enables resource autodiscovery for Redshift clusters.
        /// </summary>
        public readonly bool? EnableRedshiftAutodiscovery;
        /// <summary>
        /// Enables resource autodiscovery for S3 buckets.
        /// </summary>
        public readonly bool? EnableS3Autodiscovery;
        /// <summary>
        /// The S3 bucket ARN this Cloud Integration is allowed to use for Log Integrations.
        /// </summary>
        public readonly string? S3BucketArn;
        /// <summary>
        /// The CloudFormation template version to use when deploying `AwsCloudformationStack`. Required unless `AwsCustomerRoleArn` is set. Use `Latest` to stay in sync. See https://docs.joinformal.com/docs/changelog/cloudformation for version history.
        /// </summary>
        public readonly string? TemplateVersion;

        [OutputConstructor]
        private IntegrationCloudAws(
            bool? allowS3Access,

            ImmutableArray<string> autodiscoveryRegions,

            string? awsCustomerRoleArn,

            bool? enableEc2Autodiscovery,

            bool? enableEcsAutodiscovery,

            bool? enableEksAutodiscovery,

            bool? enableRdsAutodiscovery,

            bool? enableRedshiftAutodiscovery,

            bool? enableS3Autodiscovery,

            string? s3BucketArn,

            string? templateVersion)
        {
            AllowS3Access = allowS3Access;
            AutodiscoveryRegions = autodiscoveryRegions;
            AwsCustomerRoleArn = awsCustomerRoleArn;
            EnableEc2Autodiscovery = enableEc2Autodiscovery;
            EnableEcsAutodiscovery = enableEcsAutodiscovery;
            EnableEksAutodiscovery = enableEksAutodiscovery;
            EnableRdsAutodiscovery = enableRdsAutodiscovery;
            EnableRedshiftAutodiscovery = enableRedshiftAutodiscovery;
            EnableS3Autodiscovery = enableS3Autodiscovery;
            S3BucketArn = s3BucketArn;
            TemplateVersion = templateVersion;
        }
    }
}
