// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class IntegrationBiMetabase
    {
        /// <summary>
        /// Metabase server hostname. Required when `sync=true`.
        /// </summary>
        public readonly string? Hostname;
        /// <summary>
        /// Metabase admin password. Required when `sync=true`.
        /// </summary>
        public readonly string? Password;
        /// <summary>
        /// Metabase admin username. Required when `sync=true`.
        /// </summary>
        public readonly string? Username;

        [OutputConstructor]
        private IntegrationBiMetabase(
            string? hostname,

            string? password,

            string? username)
        {
            Hostname = hostname;
            Password = password;
            Username = username;
        }
    }
}
