// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogConfigurationResponse
    {
        /// <summary>
        /// Whether to encrypt response payloads.
        /// </summary>
        public readonly bool Encrypt;
        /// <summary>
        /// Maximum size of response payloads to log.
        /// </summary>
        public readonly int? MaxPayloadSize;
        /// <summary>
        /// Duration to retain policy evaluation inputs for responses. Valid values: 1d, 2d, 3d, 7d, 14d, 21d, 30d.
        /// </summary>
        public readonly string? PolicyEvalInputRetention;

        [OutputConstructor]
        private LogConfigurationResponse(
            bool encrypt,

            int? maxPayloadSize,

            string? policyEvalInputRetention)
        {
            Encrypt = encrypt;
            MaxPayloadSize = maxPayloadSize;
            PolicyEvalInputRetention = policyEvalInputRetention;
        }
    }
}
