// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogRewritePath
    {
        /// <summary>
        /// Whether to remove the field from the log.
        /// </summary>
        public readonly bool? Drop;
        /// <summary>
        /// Whether to encrypt the string field.
        /// </summary>
        public readonly bool? Encrypt;
        /// <summary>
        /// Whether to encrypt literal values in a SQL query.
        /// </summary>
        public readonly bool? EncryptSql;
        /// <summary>
        /// The protobuf field path, starting with `Log`.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// Whether to remove literal values from a SQL query.
        /// </summary>
        public readonly bool? StripSql;
        /// <summary>
        /// Truncates the string field to a maximum UTF-8 byte length.
        /// </summary>
        public readonly Outputs.LogRewritePathTruncate? Truncate;

        [OutputConstructor]
        private LogRewritePath(
            bool? drop,

            bool? encrypt,

            bool? encryptSql,

            string name,

            bool? stripSql,

            Outputs.LogRewritePathTruncate? truncate)
        {
            Drop = drop;
            Encrypt = encrypt;
            EncryptSql = encryptSql;
            Name = name;
            StripSql = stripSql;
            Truncate = truncate;
        }
    }
}
