// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class LogRewritePathTruncate
    {
        /// <summary>
        /// The maximum field size in bytes.
        /// </summary>
        public readonly int MaxSizeBytes;

        [OutputConstructor]
        private LogRewritePathTruncate(int maxSizeBytes)
        {
            MaxSizeBytes = maxSizeBytes;
        }
    }
}
