// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class NativeUserV3SnowflakeKey
    {
        /// <summary>
        /// The private key. Set exactly one of `Literal`, `LiteralWo` or `EnvironmentVariable`.
        /// </summary>
        public readonly Outputs.NativeUserV3SnowflakeKeyKey Key;
        /// <summary>
        /// The Snowflake username to authenticate as.
        /// </summary>
        public readonly string Username;

        [OutputConstructor]
        private NativeUserV3SnowflakeKey(
            Outputs.NativeUserV3SnowflakeKeyKey key,

            string username)
        {
            Key = key;
            Username = username;
        }
    }
}
