// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class NativeUserV3Hook
    {
        /// <summary>
        /// Environment variables the hook may read.
        /// </summary>
        public readonly ImmutableArray<string> AllowlistedEnvVariables;
        /// <summary>
        /// Network hosts the hook may access.
        /// </summary>
        public readonly ImmutableArray<string> AllowlistedNetworkHosts;
        /// <summary>
        /// The TypeScript or JavaScript source of the hook, in the same form as `formal_hook.code`.
        /// </summary>
        public readonly string Code;
        /// <summary>
        /// The credential shape the hook must return, so the connector can validate its result. One of: `Basic`, `AwsIam`, `AwsIamRole`, `GcpIam`, `AzureIam`, `KubernetesPath`, `KubernetesInline`, `SshKey`, `SnowflakeKey`, `HttpBasic`, `HttpBearer`, `HttpApiKeyHeader`, `HttpApiKeyQuery`.
        /// </summary>
        public readonly string OutputType;

        [OutputConstructor]
        private NativeUserV3Hook(
            ImmutableArray<string> allowlistedEnvVariables,

            ImmutableArray<string> allowlistedNetworkHosts,

            string code,

            string outputType)
        {
            AllowlistedEnvVariables = allowlistedEnvVariables;
            AllowlistedNetworkHosts = allowlistedNetworkHosts;
            Code = code;
            OutputType = outputType;
        }
    }
}
