// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class NativeUserV3HttpApiKeyQuery
    {
        /// <summary>
        /// The name of the query parameter carrying the API key.
        /// </summary>
        public readonly string Key;
        /// <summary>
        /// The API key. Set exactly one of `Literal`, `LiteralWo` or `EnvironmentVariable`.
        /// </summary>
        public readonly Outputs.NativeUserV3HttpApiKeyQueryValue Value;

        [OutputConstructor]
        private NativeUserV3HttpApiKeyQuery(
            string key,

            Outputs.NativeUserV3HttpApiKeyQueryValue value)
        {
            Key = key;
            Value = value;
        }
    }
}
