// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Outputs
{

    [OutputType]
    public sealed class NativeUserV3HttpBearer
    {
        /// <summary>
        /// The header to inject the token on, for example `Authorization`.
        /// </summary>
        public readonly string Header;
        /// <summary>
        /// The bearer token. Set exactly one of `Literal`, `LiteralWo` or `EnvironmentVariable`.
        /// </summary>
        public readonly Outputs.NativeUserV3HttpBearerToken Token;

        [OutputConstructor]
        private NativeUserV3HttpBearer(
            string header,

            Outputs.NativeUserV3HttpBearerToken token)
        {
            Header = header;
            Token = token;
        }
    }
}
