# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['IntegrationOidcArgs', 'IntegrationOidc']

@pulumi.input_type
class IntegrationOidcArgs:
    def __init__(__self__, *,
                 issuer: pulumi.Input[_builtins.str],
                 machine_user_id: pulumi.Input[_builtins.str],
                 claim_condition: pulumi.Input[Optional[_builtins.str]] = None,
                 end_user_email_expression: pulumi.Input[Optional[_builtins.str]] = None,
                 jwks_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a IntegrationOidc resource.

        :param pulumi.Input[_builtins.str] issuer: OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        :param pulumi.Input[_builtins.str] machine_user_id: ID of the Formal machine user that authenticated OIDC tokens map to.
        :param pulumi.Input[_builtins.str] claim_condition: CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `true`.
        :param pulumi.Input[_builtins.str] end_user_email_expression: Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        :param pulumi.Input[_builtins.str] jwks_uri: Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        :param pulumi.Input[_builtins.str] name: Friendly name for the OIDC integration. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] status: Integration status. Accepted values are `active` and `draft`. Draft disables authentication.
        """
        pulumi.set(__self__, "issuer", issuer)
        pulumi.set(__self__, "machine_user_id", machine_user_id)
        if claim_condition is not None:
            pulumi.set(__self__, "claim_condition", claim_condition)
        if end_user_email_expression is not None:
            pulumi.set(__self__, "end_user_email_expression", end_user_email_expression)
        if jwks_uri is not None:
            pulumi.set(__self__, "jwks_uri", jwks_uri)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> pulumi.Input[_builtins.str]:
        """
        OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        """
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "issuer", value)

    @_builtins.property
    @pulumi.getter(name="machineUserId")
    def machine_user_id(self) -> pulumi.Input[_builtins.str]:
        """
        ID of the Formal machine user that authenticated OIDC tokens map to.
        """
        return pulumi.get(self, "machine_user_id")

    @machine_user_id.setter
    def machine_user_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "machine_user_id", value)

    @_builtins.property
    @pulumi.getter(name="claimCondition")
    def claim_condition(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `true`.
        """
        return pulumi.get(self, "claim_condition")

    @claim_condition.setter
    def claim_condition(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "claim_condition", value)

    @_builtins.property
    @pulumi.getter(name="endUserEmailExpression")
    def end_user_email_expression(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        """
        return pulumi.get(self, "end_user_email_expression")

    @end_user_email_expression.setter
    def end_user_email_expression(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "end_user_email_expression", value)

    @_builtins.property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        """
        return pulumi.get(self, "jwks_uri")

    @jwks_uri.setter
    def jwks_uri(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "jwks_uri", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Friendly name for the OIDC integration. Must be unique within the organization.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Integration status. Accepted values are `active` and `draft`. Draft disables authentication.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)


@pulumi.input_type
class _IntegrationOidcState:
    def __init__(__self__, *,
                 audience: pulumi.Input[Optional[_builtins.str]] = None,
                 claim_condition: pulumi.Input[Optional[_builtins.str]] = None,
                 created_at: pulumi.Input[Optional[_builtins.str]] = None,
                 end_user_email_expression: pulumi.Input[Optional[_builtins.str]] = None,
                 issuer: pulumi.Input[Optional[_builtins.str]] = None,
                 jwks_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 machine_user_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 updated_at: pulumi.Input[Optional[_builtins.str]] = None):
        """
        Input properties used for looking up and filtering IntegrationOidc resources.

        :param pulumi.Input[_builtins.str] audience: The Formal audience value that tokens must present: `oidc.formal.ai/{id}`.
        :param pulumi.Input[_builtins.str] claim_condition: CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `true`.
        :param pulumi.Input[_builtins.str] created_at: When the integration was created.
        :param pulumi.Input[_builtins.str] end_user_email_expression: Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        :param pulumi.Input[_builtins.str] issuer: OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        :param pulumi.Input[_builtins.str] jwks_uri: Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        :param pulumi.Input[_builtins.str] machine_user_id: ID of the Formal machine user that authenticated OIDC tokens map to.
        :param pulumi.Input[_builtins.str] name: Friendly name for the OIDC integration. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] status: Integration status. Accepted values are `active` and `draft`. Draft disables authentication.
        :param pulumi.Input[_builtins.str] updated_at: When the integration was last updated.
        """
        if audience is not None:
            pulumi.set(__self__, "audience", audience)
        if claim_condition is not None:
            pulumi.set(__self__, "claim_condition", claim_condition)
        if created_at is not None:
            pulumi.set(__self__, "created_at", created_at)
        if end_user_email_expression is not None:
            pulumi.set(__self__, "end_user_email_expression", end_user_email_expression)
        if issuer is not None:
            pulumi.set(__self__, "issuer", issuer)
        if jwks_uri is not None:
            pulumi.set(__self__, "jwks_uri", jwks_uri)
        if machine_user_id is not None:
            pulumi.set(__self__, "machine_user_id", machine_user_id)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if status is not None:
            pulumi.set(__self__, "status", status)
        if updated_at is not None:
            pulumi.set(__self__, "updated_at", updated_at)

    @_builtins.property
    @pulumi.getter
    def audience(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The Formal audience value that tokens must present: `oidc.formal.ai/{id}`.
        """
        return pulumi.get(self, "audience")

    @audience.setter
    def audience(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "audience", value)

    @_builtins.property
    @pulumi.getter(name="claimCondition")
    def claim_condition(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `true`.
        """
        return pulumi.get(self, "claim_condition")

    @claim_condition.setter
    def claim_condition(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "claim_condition", value)

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        When the integration was created.
        """
        return pulumi.get(self, "created_at")

    @created_at.setter
    def created_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "created_at", value)

    @_builtins.property
    @pulumi.getter(name="endUserEmailExpression")
    def end_user_email_expression(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        """
        return pulumi.get(self, "end_user_email_expression")

    @end_user_email_expression.setter
    def end_user_email_expression(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "end_user_email_expression", value)

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        """
        return pulumi.get(self, "issuer")

    @issuer.setter
    def issuer(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "issuer", value)

    @_builtins.property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        """
        return pulumi.get(self, "jwks_uri")

    @jwks_uri.setter
    def jwks_uri(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "jwks_uri", value)

    @_builtins.property
    @pulumi.getter(name="machineUserId")
    def machine_user_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        ID of the Formal machine user that authenticated OIDC tokens map to.
        """
        return pulumi.get(self, "machine_user_id")

    @machine_user_id.setter
    def machine_user_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "machine_user_id", value)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Friendly name for the OIDC integration. Must be unique within the organization.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Integration status. Accepted values are `active` and `draft`. Draft disables authentication.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "status", value)

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        When the integration was last updated.
        """
        return pulumi.get(self, "updated_at")

    @updated_at.setter
    def updated_at(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "updated_at", value)


@pulumi.type_token("formal:index/integrationOidc:IntegrationOidc")
class IntegrationOidc(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 claim_condition: pulumi.Input[Optional[_builtins.str]] = None,
                 end_user_email_expression: pulumi.Input[Optional[_builtins.str]] = None,
                 issuer: pulumi.Input[Optional[_builtins.str]] = None,
                 jwks_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 machine_user_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        Registers an OIDC trust configuration used to authenticate externally signed JWTs to the Formal control plane as a machine user.


        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] claim_condition: CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `true`.
        :param pulumi.Input[_builtins.str] end_user_email_expression: Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        :param pulumi.Input[_builtins.str] issuer: OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        :param pulumi.Input[_builtins.str] jwks_uri: Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        :param pulumi.Input[_builtins.str] machine_user_id: ID of the Formal machine user that authenticated OIDC tokens map to.
        :param pulumi.Input[_builtins.str] name: Friendly name for the OIDC integration. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] status: Integration status. Accepted values are `active` and `draft`. Draft disables authentication.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: IntegrationOidcArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Registers an OIDC trust configuration used to authenticate externally signed JWTs to the Formal control plane as a machine user.


        :param str resource_name: The name of the resource.
        :param IntegrationOidcArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(IntegrationOidcArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 claim_condition: pulumi.Input[Optional[_builtins.str]] = None,
                 end_user_email_expression: pulumi.Input[Optional[_builtins.str]] = None,
                 issuer: pulumi.Input[Optional[_builtins.str]] = None,
                 jwks_uri: pulumi.Input[Optional[_builtins.str]] = None,
                 machine_user_id: pulumi.Input[Optional[_builtins.str]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 status: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = IntegrationOidcArgs.__new__(IntegrationOidcArgs)

            __props__.__dict__["claim_condition"] = claim_condition
            __props__.__dict__["end_user_email_expression"] = end_user_email_expression
            if issuer is None and not opts.urn:
                raise TypeError("Missing required property 'issuer'")
            __props__.__dict__["issuer"] = issuer
            __props__.__dict__["jwks_uri"] = jwks_uri
            if machine_user_id is None and not opts.urn:
                raise TypeError("Missing required property 'machine_user_id'")
            __props__.__dict__["machine_user_id"] = machine_user_id
            __props__.__dict__["name"] = name
            __props__.__dict__["status"] = status
            __props__.__dict__["audience"] = None
            __props__.__dict__["created_at"] = None
            __props__.__dict__["updated_at"] = None
        super(IntegrationOidc, __self__).__init__(
            'formal:index/integrationOidc:IntegrationOidc',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            audience: pulumi.Input[Optional[_builtins.str]] = None,
            claim_condition: pulumi.Input[Optional[_builtins.str]] = None,
            created_at: pulumi.Input[Optional[_builtins.str]] = None,
            end_user_email_expression: pulumi.Input[Optional[_builtins.str]] = None,
            issuer: pulumi.Input[Optional[_builtins.str]] = None,
            jwks_uri: pulumi.Input[Optional[_builtins.str]] = None,
            machine_user_id: pulumi.Input[Optional[_builtins.str]] = None,
            name: pulumi.Input[Optional[_builtins.str]] = None,
            status: pulumi.Input[Optional[_builtins.str]] = None,
            updated_at: pulumi.Input[Optional[_builtins.str]] = None) -> 'IntegrationOidc':
        """
        Get an existing IntegrationOidc resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] audience: The Formal audience value that tokens must present: `oidc.formal.ai/{id}`.
        :param pulumi.Input[_builtins.str] claim_condition: CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `true`.
        :param pulumi.Input[_builtins.str] created_at: When the integration was created.
        :param pulumi.Input[_builtins.str] end_user_email_expression: Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        :param pulumi.Input[_builtins.str] issuer: OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        :param pulumi.Input[_builtins.str] jwks_uri: Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        :param pulumi.Input[_builtins.str] machine_user_id: ID of the Formal machine user that authenticated OIDC tokens map to.
        :param pulumi.Input[_builtins.str] name: Friendly name for the OIDC integration. Must be unique within the organization.
        :param pulumi.Input[_builtins.str] status: Integration status. Accepted values are `active` and `draft`. Draft disables authentication.
        :param pulumi.Input[_builtins.str] updated_at: When the integration was last updated.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _IntegrationOidcState.__new__(_IntegrationOidcState)

        __props__.__dict__["audience"] = audience
        __props__.__dict__["claim_condition"] = claim_condition
        __props__.__dict__["created_at"] = created_at
        __props__.__dict__["end_user_email_expression"] = end_user_email_expression
        __props__.__dict__["issuer"] = issuer
        __props__.__dict__["jwks_uri"] = jwks_uri
        __props__.__dict__["machine_user_id"] = machine_user_id
        __props__.__dict__["name"] = name
        __props__.__dict__["status"] = status
        __props__.__dict__["updated_at"] = updated_at
        return IntegrationOidc(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def audience(self) -> pulumi.Output[_builtins.str]:
        """
        The Formal audience value that tokens must present: `oidc.formal.ai/{id}`.
        """
        return pulumi.get(self, "audience")

    @_builtins.property
    @pulumi.getter(name="claimCondition")
    def claim_condition(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        CEL expression evaluated against verified token claims. Must return a boolean. Defaults to `true`.
        """
        return pulumi.get(self, "claim_condition")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        When the integration was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter(name="endUserEmailExpression")
    def end_user_email_expression(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional CEL expression over verified token claims that must evaluate to a string email. When set, federation mint resolves a Formal human by case-insensitive email. Leave unset for machine-only trusts. Examples: `claims.owner_email` (Cursor); `claims.sub.split('/').last()` (AWSReservedSSO session name when the session name is an email).
        """
        return pulumi.get(self, "end_user_email_expression")

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> pulumi.Output[_builtins.str]:
        """
        OIDC issuer URL. Must be absolute HTTPS (path preserved). In local `ENV=dev`, the configured fake OIDC provider origin may use HTTP.
        """
        return pulumi.get(self, "issuer")

    @_builtins.property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Optional JWKS URI. When unset, Formal uses OIDC Discovery from the issuer. Must be absolute HTTPS when set.
        """
        return pulumi.get(self, "jwks_uri")

    @_builtins.property
    @pulumi.getter(name="machineUserId")
    def machine_user_id(self) -> pulumi.Output[_builtins.str]:
        """
        ID of the Formal machine user that authenticated OIDC tokens map to.
        """
        return pulumi.get(self, "machine_user_id")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        Friendly name for the OIDC integration. Must be unique within the organization.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def status(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Integration status. Accepted values are `active` and `draft`. Draft disables authentication.
        """
        return pulumi.get(self, "status")

    @_builtins.property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> pulumi.Output[_builtins.str]:
        """
        When the integration was last updated.
        """
        return pulumi.get(self, "updated_at")

