// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package formal

import (
	"context"
	"reflect"

	"github.com/formalco/pulumi-formal/sdk/go/formal/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Data source for looking up a Space by ID or by name. Use either `id` or `name`, but not both.
func LookupSpace(ctx *pulumi.Context, args *LookupSpaceArgs, opts ...pulumi.InvokeOption) (*LookupSpaceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSpaceResult
	err := ctx.Invoke("formal:index/getSpace:getSpace", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSpace.
type LookupSpaceArgs struct {
	// The Formal ID for this Space.
	Id *string `pulumi:"id"`
	// The name of the Space to look up. Use this to fetch a space by name.
	Name *string `pulumi:"name"`
}

// A collection of values returned by getSpace.
type LookupSpaceResult struct {
	// Creation time of the Space.
	CreatedAt int `pulumi:"createdAt"`
	// Description of the Space.
	Description string `pulumi:"description"`
	// The Formal ID for this Space.
	Id *string `pulumi:"id"`
	// The name of the Space to look up. Use this to fetch a space by name.
	Name *string `pulumi:"name"`
	// If set to true, this Space cannot be deleted.
	TerminationProtection bool `pulumi:"terminationProtection"`
}

func LookupSpaceOutput(ctx *pulumi.Context, args LookupSpaceOutputArgs, opts ...pulumi.InvokeOption) LookupSpaceResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupSpaceResultOutput, error) {
			args := v.(LookupSpaceArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("formal:index/getSpace:getSpace", args, LookupSpaceResultOutput{}, options).(LookupSpaceResultOutput), nil
		}).(LookupSpaceResultOutput)
}

// A collection of arguments for invoking getSpace.
type LookupSpaceOutputArgs struct {
	// The Formal ID for this Space.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// The name of the Space to look up. Use this to fetch a space by name.
	Name pulumi.StringPtrInput `pulumi:"name"`
}

func (LookupSpaceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSpaceArgs)(nil)).Elem()
}

// A collection of values returned by getSpace.
type LookupSpaceResultOutput struct{ *pulumi.OutputState }

func (LookupSpaceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSpaceResult)(nil)).Elem()
}

func (o LookupSpaceResultOutput) ToLookupSpaceResultOutput() LookupSpaceResultOutput {
	return o
}

func (o LookupSpaceResultOutput) ToLookupSpaceResultOutputWithContext(ctx context.Context) LookupSpaceResultOutput {
	return o
}

// Creation time of the Space.
func (o LookupSpaceResultOutput) CreatedAt() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSpaceResult) int { return v.CreatedAt }).(pulumi.IntOutput)
}

// Description of the Space.
func (o LookupSpaceResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSpaceResult) string { return v.Description }).(pulumi.StringOutput)
}

// The Formal ID for this Space.
func (o LookupSpaceResultOutput) Id() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSpaceResult) *string { return v.Id }).(pulumi.StringPtrOutput)
}

// The name of the Space to look up. Use this to fetch a space by name.
func (o LookupSpaceResultOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupSpaceResult) *string { return v.Name }).(pulumi.StringPtrOutput)
}

// If set to true, this Space cannot be deleted.
func (o LookupSpaceResultOutput) TerminationProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSpaceResult) bool { return v.TerminationProtection }).(pulumi.BoolOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSpaceResultOutput{})
}
