// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package formal

import (
	"context"
	"reflect"

	"errors"
	"github.com/formalco/pulumi-formal/sdk/go/formal/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Hooks are JavaScript functions evaluated during policy decisions. Policies reference hooks as `input.hooks.<name>`.
type Hook struct {
	pulumi.CustomResourceState

	// Names of process environment variables the hook may read via its second `env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `env`.
	AllowlistedEnvironmentVariables pulumi.StringArrayOutput `pulumi:"allowlistedEnvironmentVariables"`
	// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
	AllowlistedNetworkHosts pulumi.StringArrayOutput `pulumi:"allowlistedNetworkHosts"`
	// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
	Code pulumi.StringOutput `pulumi:"code"`
	// When the hook was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The hook description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.<name>`.
	Name pulumi.StringOutput `pulumi:"name"`
	// The hook status. Accepted values are `active` and `draft`. Only active hooks can be referenced by policies.
	Status pulumi.StringPtrOutput `pulumi:"status"`
	// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
	TimeoutMs pulumi.IntPtrOutput `pulumi:"timeoutMs"`
	// When the hook was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewHook registers a new resource with the given unique name, arguments, and options.
func NewHook(ctx *pulumi.Context,
	name string, args *HookArgs, opts ...pulumi.ResourceOption) (*Hook, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Code == nil {
		return nil, errors.New("invalid value for required argument 'Code'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Hook
	err := ctx.RegisterResource("formal:index/hook:Hook", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetHook gets an existing Hook resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetHook(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *HookState, opts ...pulumi.ResourceOption) (*Hook, error) {
	var resource Hook
	err := ctx.ReadResource("formal:index/hook:Hook", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Hook resources.
type hookState struct {
	// Names of process environment variables the hook may read via its second `env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `env`.
	AllowlistedEnvironmentVariables []string `pulumi:"allowlistedEnvironmentVariables"`
	// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
	AllowlistedNetworkHosts []string `pulumi:"allowlistedNetworkHosts"`
	// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
	Code *string `pulumi:"code"`
	// When the hook was created.
	CreatedAt *string `pulumi:"createdAt"`
	// The hook description.
	Description *string `pulumi:"description"`
	// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.<name>`.
	Name *string `pulumi:"name"`
	// The hook status. Accepted values are `active` and `draft`. Only active hooks can be referenced by policies.
	Status *string `pulumi:"status"`
	// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
	TimeoutMs *int `pulumi:"timeoutMs"`
	// When the hook was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type HookState struct {
	// Names of process environment variables the hook may read via its second `env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `env`.
	AllowlistedEnvironmentVariables pulumi.StringArrayInput
	// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
	AllowlistedNetworkHosts pulumi.StringArrayInput
	// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
	Code pulumi.StringPtrInput
	// When the hook was created.
	CreatedAt pulumi.StringPtrInput
	// The hook description.
	Description pulumi.StringPtrInput
	// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.<name>`.
	Name pulumi.StringPtrInput
	// The hook status. Accepted values are `active` and `draft`. Only active hooks can be referenced by policies.
	Status pulumi.StringPtrInput
	// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
	TimeoutMs pulumi.IntPtrInput
	// When the hook was last updated.
	UpdatedAt pulumi.StringPtrInput
}

func (HookState) ElementType() reflect.Type {
	return reflect.TypeOf((*hookState)(nil)).Elem()
}

type hookArgs struct {
	// Names of process environment variables the hook may read via its second `env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `env`.
	AllowlistedEnvironmentVariables []string `pulumi:"allowlistedEnvironmentVariables"`
	// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
	AllowlistedNetworkHosts []string `pulumi:"allowlistedNetworkHosts"`
	// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
	Code string `pulumi:"code"`
	// The hook description.
	Description *string `pulumi:"description"`
	// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.<name>`.
	Name *string `pulumi:"name"`
	// The hook status. Accepted values are `active` and `draft`. Only active hooks can be referenced by policies.
	Status *string `pulumi:"status"`
	// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
	TimeoutMs *int `pulumi:"timeoutMs"`
}

// The set of arguments for constructing a Hook resource.
type HookArgs struct {
	// Names of process environment variables the hook may read via its second `env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `env`.
	AllowlistedEnvironmentVariables pulumi.StringArrayInput
	// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
	AllowlistedNetworkHosts pulumi.StringArrayInput
	// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
	Code pulumi.StringInput
	// The hook description.
	Description pulumi.StringPtrInput
	// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.<name>`.
	Name pulumi.StringPtrInput
	// The hook status. Accepted values are `active` and `draft`. Only active hooks can be referenced by policies.
	Status pulumi.StringPtrInput
	// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
	TimeoutMs pulumi.IntPtrInput
}

func (HookArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*hookArgs)(nil)).Elem()
}

type HookInput interface {
	pulumi.Input

	ToHookOutput() HookOutput
	ToHookOutputWithContext(ctx context.Context) HookOutput
}

func (*Hook) ElementType() reflect.Type {
	return reflect.TypeOf((**Hook)(nil)).Elem()
}

func (i *Hook) ToHookOutput() HookOutput {
	return i.ToHookOutputWithContext(context.Background())
}

func (i *Hook) ToHookOutputWithContext(ctx context.Context) HookOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HookOutput)
}

// HookArrayInput is an input type that accepts HookArray and HookArrayOutput values.
// You can construct a concrete instance of `HookArrayInput` via:
//
//	HookArray{ HookArgs{...} }
type HookArrayInput interface {
	pulumi.Input

	ToHookArrayOutput() HookArrayOutput
	ToHookArrayOutputWithContext(context.Context) HookArrayOutput
}

type HookArray []HookInput

func (HookArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Hook)(nil)).Elem()
}

func (i HookArray) ToHookArrayOutput() HookArrayOutput {
	return i.ToHookArrayOutputWithContext(context.Background())
}

func (i HookArray) ToHookArrayOutputWithContext(ctx context.Context) HookArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HookArrayOutput)
}

// HookMapInput is an input type that accepts HookMap and HookMapOutput values.
// You can construct a concrete instance of `HookMapInput` via:
//
//	HookMap{ "key": HookArgs{...} }
type HookMapInput interface {
	pulumi.Input

	ToHookMapOutput() HookMapOutput
	ToHookMapOutputWithContext(context.Context) HookMapOutput
}

type HookMap map[string]HookInput

func (HookMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Hook)(nil)).Elem()
}

func (i HookMap) ToHookMapOutput() HookMapOutput {
	return i.ToHookMapOutputWithContext(context.Background())
}

func (i HookMap) ToHookMapOutputWithContext(ctx context.Context) HookMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(HookMapOutput)
}

type HookOutput struct{ *pulumi.OutputState }

func (HookOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Hook)(nil)).Elem()
}

func (o HookOutput) ToHookOutput() HookOutput {
	return o
}

func (o HookOutput) ToHookOutputWithContext(ctx context.Context) HookOutput {
	return o
}

// Names of process environment variables the hook may read via its second `env` argument at evaluation time. Each name must match `^[A-Za-z_][A-Za-z0-9_]*$`. Variables that are unset on the connector or desktop process are omitted from `env`.
func (o HookOutput) AllowlistedEnvironmentVariables() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringArrayOutput { return v.AllowlistedEnvironmentVariables }).(pulumi.StringArrayOutput)
}

// Hostnames and IP addresses the hook may contact at evaluation time. Schemes, paths, and ports are not accepted. All ports on each host are allowed.
func (o HookOutput) AllowlistedNetworkHosts() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringArrayOutput { return v.AllowlistedNetworkHosts }).(pulumi.StringArrayOutput)
}

// The hook implementation as JavaScript. Must be a default-exported function (for example `export default function hook(input, env) { ... }`). The optional second argument receives allowlisted process environment variables.
func (o HookOutput) Code() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.Code }).(pulumi.StringOutput)
}

// When the hook was created.
func (o HookOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The hook description.
func (o HookOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The name of the hook. Must be unique within the organization and match `^[A-Za-z_][A-Za-z0-9_]*$`. Policies reference this name as `input.hooks.<name>`.
func (o HookOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The hook status. Accepted values are `active` and `draft`. Only active hooks can be referenced by policies.
func (o HookOutput) Status() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringPtrOutput { return v.Status }).(pulumi.StringPtrOutput)
}

// Maximum time in milliseconds the hook may run during policy evaluation. Must be between 1 and 60000.
func (o HookOutput) TimeoutMs() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Hook) pulumi.IntPtrOutput { return v.TimeoutMs }).(pulumi.IntPtrOutput)
}

// When the hook was last updated.
func (o HookOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *Hook) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type HookArrayOutput struct{ *pulumi.OutputState }

func (HookArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*Hook)(nil)).Elem()
}

func (o HookArrayOutput) ToHookArrayOutput() HookArrayOutput {
	return o
}

func (o HookArrayOutput) ToHookArrayOutputWithContext(ctx context.Context) HookArrayOutput {
	return o
}

func (o HookArrayOutput) Index(i pulumi.IntInput) HookOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *Hook {
		return vs[0].([]*Hook)[vs[1].(int)]
	}).(HookOutput)
}

type HookMapOutput struct{ *pulumi.OutputState }

func (HookMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*Hook)(nil)).Elem()
}

func (o HookMapOutput) ToHookMapOutput() HookMapOutput {
	return o
}

func (o HookMapOutput) ToHookMapOutputWithContext(ctx context.Context) HookMapOutput {
	return o
}

func (o HookMapOutput) MapIndex(k pulumi.StringInput) HookOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *Hook {
		return vs[0].(map[string]*Hook)[vs[1].(string)]
	}).(HookOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*HookInput)(nil)).Elem(), &Hook{})
	pulumi.RegisterInputType(reflect.TypeOf((*HookArrayInput)(nil)).Elem(), HookArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*HookMapInput)(nil)).Elem(), HookMap{})
	pulumi.RegisterOutputType(HookOutput{})
	pulumi.RegisterOutputType(HookArrayOutput{})
	pulumi.RegisterOutputType(HookMapOutput{})
}
