// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package formal

import (
	"context"
	"reflect"

	"errors"
	"github.com/formalco/pulumi-formal/sdk/go/formal/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Reports the GCP service account and workload identity pool provider back to Formal to activate a GCP Cloud Integration.
type IntegrationCloudGcpActivation struct {
	pulumi.CustomResourceState

	// The ID of the GCP Cloud Integration to activate.
	IntegrationId pulumi.StringOutput `pulumi:"integrationId"`
	// The GCP service account email created for this integration.
	ServiceAccountEmail pulumi.StringOutput `pulumi:"serviceAccountEmail"`
	// The GCP workload identity pool provider created for this integration.
	WorkloadIdentityPoolProvider pulumi.StringOutput `pulumi:"workloadIdentityPoolProvider"`
}

// NewIntegrationCloudGcpActivation registers a new resource with the given unique name, arguments, and options.
func NewIntegrationCloudGcpActivation(ctx *pulumi.Context,
	name string, args *IntegrationCloudGcpActivationArgs, opts ...pulumi.ResourceOption) (*IntegrationCloudGcpActivation, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.IntegrationId == nil {
		return nil, errors.New("invalid value for required argument 'IntegrationId'")
	}
	if args.ServiceAccountEmail == nil {
		return nil, errors.New("invalid value for required argument 'ServiceAccountEmail'")
	}
	if args.WorkloadIdentityPoolProvider == nil {
		return nil, errors.New("invalid value for required argument 'WorkloadIdentityPoolProvider'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource IntegrationCloudGcpActivation
	err := ctx.RegisterResource("formal:index/integrationCloudGcpActivation:IntegrationCloudGcpActivation", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetIntegrationCloudGcpActivation gets an existing IntegrationCloudGcpActivation resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetIntegrationCloudGcpActivation(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *IntegrationCloudGcpActivationState, opts ...pulumi.ResourceOption) (*IntegrationCloudGcpActivation, error) {
	var resource IntegrationCloudGcpActivation
	err := ctx.ReadResource("formal:index/integrationCloudGcpActivation:IntegrationCloudGcpActivation", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering IntegrationCloudGcpActivation resources.
type integrationCloudGcpActivationState struct {
	// The ID of the GCP Cloud Integration to activate.
	IntegrationId *string `pulumi:"integrationId"`
	// The GCP service account email created for this integration.
	ServiceAccountEmail *string `pulumi:"serviceAccountEmail"`
	// The GCP workload identity pool provider created for this integration.
	WorkloadIdentityPoolProvider *string `pulumi:"workloadIdentityPoolProvider"`
}

type IntegrationCloudGcpActivationState struct {
	// The ID of the GCP Cloud Integration to activate.
	IntegrationId pulumi.StringPtrInput
	// The GCP service account email created for this integration.
	ServiceAccountEmail pulumi.StringPtrInput
	// The GCP workload identity pool provider created for this integration.
	WorkloadIdentityPoolProvider pulumi.StringPtrInput
}

func (IntegrationCloudGcpActivationState) ElementType() reflect.Type {
	return reflect.TypeOf((*integrationCloudGcpActivationState)(nil)).Elem()
}

type integrationCloudGcpActivationArgs struct {
	// The ID of the GCP Cloud Integration to activate.
	IntegrationId string `pulumi:"integrationId"`
	// The GCP service account email created for this integration.
	ServiceAccountEmail string `pulumi:"serviceAccountEmail"`
	// The GCP workload identity pool provider created for this integration.
	WorkloadIdentityPoolProvider string `pulumi:"workloadIdentityPoolProvider"`
}

// The set of arguments for constructing a IntegrationCloudGcpActivation resource.
type IntegrationCloudGcpActivationArgs struct {
	// The ID of the GCP Cloud Integration to activate.
	IntegrationId pulumi.StringInput
	// The GCP service account email created for this integration.
	ServiceAccountEmail pulumi.StringInput
	// The GCP workload identity pool provider created for this integration.
	WorkloadIdentityPoolProvider pulumi.StringInput
}

func (IntegrationCloudGcpActivationArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*integrationCloudGcpActivationArgs)(nil)).Elem()
}

type IntegrationCloudGcpActivationInput interface {
	pulumi.Input

	ToIntegrationCloudGcpActivationOutput() IntegrationCloudGcpActivationOutput
	ToIntegrationCloudGcpActivationOutputWithContext(ctx context.Context) IntegrationCloudGcpActivationOutput
}

func (*IntegrationCloudGcpActivation) ElementType() reflect.Type {
	return reflect.TypeOf((**IntegrationCloudGcpActivation)(nil)).Elem()
}

func (i *IntegrationCloudGcpActivation) ToIntegrationCloudGcpActivationOutput() IntegrationCloudGcpActivationOutput {
	return i.ToIntegrationCloudGcpActivationOutputWithContext(context.Background())
}

func (i *IntegrationCloudGcpActivation) ToIntegrationCloudGcpActivationOutputWithContext(ctx context.Context) IntegrationCloudGcpActivationOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationCloudGcpActivationOutput)
}

// IntegrationCloudGcpActivationArrayInput is an input type that accepts IntegrationCloudGcpActivationArray and IntegrationCloudGcpActivationArrayOutput values.
// You can construct a concrete instance of `IntegrationCloudGcpActivationArrayInput` via:
//
//	IntegrationCloudGcpActivationArray{ IntegrationCloudGcpActivationArgs{...} }
type IntegrationCloudGcpActivationArrayInput interface {
	pulumi.Input

	ToIntegrationCloudGcpActivationArrayOutput() IntegrationCloudGcpActivationArrayOutput
	ToIntegrationCloudGcpActivationArrayOutputWithContext(context.Context) IntegrationCloudGcpActivationArrayOutput
}

type IntegrationCloudGcpActivationArray []IntegrationCloudGcpActivationInput

func (IntegrationCloudGcpActivationArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IntegrationCloudGcpActivation)(nil)).Elem()
}

func (i IntegrationCloudGcpActivationArray) ToIntegrationCloudGcpActivationArrayOutput() IntegrationCloudGcpActivationArrayOutput {
	return i.ToIntegrationCloudGcpActivationArrayOutputWithContext(context.Background())
}

func (i IntegrationCloudGcpActivationArray) ToIntegrationCloudGcpActivationArrayOutputWithContext(ctx context.Context) IntegrationCloudGcpActivationArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationCloudGcpActivationArrayOutput)
}

// IntegrationCloudGcpActivationMapInput is an input type that accepts IntegrationCloudGcpActivationMap and IntegrationCloudGcpActivationMapOutput values.
// You can construct a concrete instance of `IntegrationCloudGcpActivationMapInput` via:
//
//	IntegrationCloudGcpActivationMap{ "key": IntegrationCloudGcpActivationArgs{...} }
type IntegrationCloudGcpActivationMapInput interface {
	pulumi.Input

	ToIntegrationCloudGcpActivationMapOutput() IntegrationCloudGcpActivationMapOutput
	ToIntegrationCloudGcpActivationMapOutputWithContext(context.Context) IntegrationCloudGcpActivationMapOutput
}

type IntegrationCloudGcpActivationMap map[string]IntegrationCloudGcpActivationInput

func (IntegrationCloudGcpActivationMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IntegrationCloudGcpActivation)(nil)).Elem()
}

func (i IntegrationCloudGcpActivationMap) ToIntegrationCloudGcpActivationMapOutput() IntegrationCloudGcpActivationMapOutput {
	return i.ToIntegrationCloudGcpActivationMapOutputWithContext(context.Background())
}

func (i IntegrationCloudGcpActivationMap) ToIntegrationCloudGcpActivationMapOutputWithContext(ctx context.Context) IntegrationCloudGcpActivationMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(IntegrationCloudGcpActivationMapOutput)
}

type IntegrationCloudGcpActivationOutput struct{ *pulumi.OutputState }

func (IntegrationCloudGcpActivationOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**IntegrationCloudGcpActivation)(nil)).Elem()
}

func (o IntegrationCloudGcpActivationOutput) ToIntegrationCloudGcpActivationOutput() IntegrationCloudGcpActivationOutput {
	return o
}

func (o IntegrationCloudGcpActivationOutput) ToIntegrationCloudGcpActivationOutputWithContext(ctx context.Context) IntegrationCloudGcpActivationOutput {
	return o
}

// The ID of the GCP Cloud Integration to activate.
func (o IntegrationCloudGcpActivationOutput) IntegrationId() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationCloudGcpActivation) pulumi.StringOutput { return v.IntegrationId }).(pulumi.StringOutput)
}

// The GCP service account email created for this integration.
func (o IntegrationCloudGcpActivationOutput) ServiceAccountEmail() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationCloudGcpActivation) pulumi.StringOutput { return v.ServiceAccountEmail }).(pulumi.StringOutput)
}

// The GCP workload identity pool provider created for this integration.
func (o IntegrationCloudGcpActivationOutput) WorkloadIdentityPoolProvider() pulumi.StringOutput {
	return o.ApplyT(func(v *IntegrationCloudGcpActivation) pulumi.StringOutput { return v.WorkloadIdentityPoolProvider }).(pulumi.StringOutput)
}

type IntegrationCloudGcpActivationArrayOutput struct{ *pulumi.OutputState }

func (IntegrationCloudGcpActivationArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*IntegrationCloudGcpActivation)(nil)).Elem()
}

func (o IntegrationCloudGcpActivationArrayOutput) ToIntegrationCloudGcpActivationArrayOutput() IntegrationCloudGcpActivationArrayOutput {
	return o
}

func (o IntegrationCloudGcpActivationArrayOutput) ToIntegrationCloudGcpActivationArrayOutputWithContext(ctx context.Context) IntegrationCloudGcpActivationArrayOutput {
	return o
}

func (o IntegrationCloudGcpActivationArrayOutput) Index(i pulumi.IntInput) IntegrationCloudGcpActivationOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *IntegrationCloudGcpActivation {
		return vs[0].([]*IntegrationCloudGcpActivation)[vs[1].(int)]
	}).(IntegrationCloudGcpActivationOutput)
}

type IntegrationCloudGcpActivationMapOutput struct{ *pulumi.OutputState }

func (IntegrationCloudGcpActivationMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*IntegrationCloudGcpActivation)(nil)).Elem()
}

func (o IntegrationCloudGcpActivationMapOutput) ToIntegrationCloudGcpActivationMapOutput() IntegrationCloudGcpActivationMapOutput {
	return o
}

func (o IntegrationCloudGcpActivationMapOutput) ToIntegrationCloudGcpActivationMapOutputWithContext(ctx context.Context) IntegrationCloudGcpActivationMapOutput {
	return o
}

func (o IntegrationCloudGcpActivationMapOutput) MapIndex(k pulumi.StringInput) IntegrationCloudGcpActivationOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *IntegrationCloudGcpActivation {
		return vs[0].(map[string]*IntegrationCloudGcpActivation)[vs[1].(string)]
	}).(IntegrationCloudGcpActivationOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationCloudGcpActivationInput)(nil)).Elem(), &IntegrationCloudGcpActivation{})
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationCloudGcpActivationArrayInput)(nil)).Elem(), IntegrationCloudGcpActivationArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*IntegrationCloudGcpActivationMapInput)(nil)).Elem(), IntegrationCloudGcpActivationMap{})
	pulumi.RegisterOutputType(IntegrationCloudGcpActivationOutput{})
	pulumi.RegisterOutputType(IntegrationCloudGcpActivationArrayOutput{})
	pulumi.RegisterOutputType(IntegrationCloudGcpActivationMapOutput{})
}
