// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package formal

import (
	"context"
	"reflect"

	"errors"
	"github.com/formalco/pulumi-formal/sdk/go/formal/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Registering an inventory object (db, schema, table, column, sub-column) with Formal. Useful for seeding the inventory in test fixtures so that connectors load it at startup instead of relying on inline discovery.
type InventoryObject struct {
	pulumi.CustomResourceState

	// Column data type (e.g. `varchar`). Required when `type` is `column`, ignored otherwise.
	DataType pulumi.StringPtrOutput `pulumi:"dataType"`
	// Last segment of the path (e.g. `email`).
	Name pulumi.StringOutput `pulumi:"name"`
	// Hierarchical path of the object (e.g. `mydb.public.users.email`).
	Path pulumi.StringOutput `pulumi:"path"`
	// Resource (datastore) ID this object belongs to.
	ResourceId pulumi.StringOutput `pulumi:"resourceId"`
	// Sub-column type. One of `json`, `hstore`. Required when `type` is `sub-column`, ignored otherwise.
	SubType pulumi.StringPtrOutput `pulumi:"subType"`
	// Object type. One of `db`, `schema`, `table`, `column`, `sub-column`.
	Type pulumi.StringOutput `pulumi:"type"`
}

// NewInventoryObject registers a new resource with the given unique name, arguments, and options.
func NewInventoryObject(ctx *pulumi.Context,
	name string, args *InventoryObjectArgs, opts ...pulumi.ResourceOption) (*InventoryObject, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Path == nil {
		return nil, errors.New("invalid value for required argument 'Path'")
	}
	if args.ResourceId == nil {
		return nil, errors.New("invalid value for required argument 'ResourceId'")
	}
	if args.Type == nil {
		return nil, errors.New("invalid value for required argument 'Type'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource InventoryObject
	err := ctx.RegisterResource("formal:index/inventoryObject:InventoryObject", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetInventoryObject gets an existing InventoryObject resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetInventoryObject(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *InventoryObjectState, opts ...pulumi.ResourceOption) (*InventoryObject, error) {
	var resource InventoryObject
	err := ctx.ReadResource("formal:index/inventoryObject:InventoryObject", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering InventoryObject resources.
type inventoryObjectState struct {
	// Column data type (e.g. `varchar`). Required when `type` is `column`, ignored otherwise.
	DataType *string `pulumi:"dataType"`
	// Last segment of the path (e.g. `email`).
	Name *string `pulumi:"name"`
	// Hierarchical path of the object (e.g. `mydb.public.users.email`).
	Path *string `pulumi:"path"`
	// Resource (datastore) ID this object belongs to.
	ResourceId *string `pulumi:"resourceId"`
	// Sub-column type. One of `json`, `hstore`. Required when `type` is `sub-column`, ignored otherwise.
	SubType *string `pulumi:"subType"`
	// Object type. One of `db`, `schema`, `table`, `column`, `sub-column`.
	Type *string `pulumi:"type"`
}

type InventoryObjectState struct {
	// Column data type (e.g. `varchar`). Required when `type` is `column`, ignored otherwise.
	DataType pulumi.StringPtrInput
	// Last segment of the path (e.g. `email`).
	Name pulumi.StringPtrInput
	// Hierarchical path of the object (e.g. `mydb.public.users.email`).
	Path pulumi.StringPtrInput
	// Resource (datastore) ID this object belongs to.
	ResourceId pulumi.StringPtrInput
	// Sub-column type. One of `json`, `hstore`. Required when `type` is `sub-column`, ignored otherwise.
	SubType pulumi.StringPtrInput
	// Object type. One of `db`, `schema`, `table`, `column`, `sub-column`.
	Type pulumi.StringPtrInput
}

func (InventoryObjectState) ElementType() reflect.Type {
	return reflect.TypeOf((*inventoryObjectState)(nil)).Elem()
}

type inventoryObjectArgs struct {
	// Column data type (e.g. `varchar`). Required when `type` is `column`, ignored otherwise.
	DataType *string `pulumi:"dataType"`
	// Last segment of the path (e.g. `email`).
	Name *string `pulumi:"name"`
	// Hierarchical path of the object (e.g. `mydb.public.users.email`).
	Path string `pulumi:"path"`
	// Resource (datastore) ID this object belongs to.
	ResourceId string `pulumi:"resourceId"`
	// Sub-column type. One of `json`, `hstore`. Required when `type` is `sub-column`, ignored otherwise.
	SubType *string `pulumi:"subType"`
	// Object type. One of `db`, `schema`, `table`, `column`, `sub-column`.
	Type string `pulumi:"type"`
}

// The set of arguments for constructing a InventoryObject resource.
type InventoryObjectArgs struct {
	// Column data type (e.g. `varchar`). Required when `type` is `column`, ignored otherwise.
	DataType pulumi.StringPtrInput
	// Last segment of the path (e.g. `email`).
	Name pulumi.StringPtrInput
	// Hierarchical path of the object (e.g. `mydb.public.users.email`).
	Path pulumi.StringInput
	// Resource (datastore) ID this object belongs to.
	ResourceId pulumi.StringInput
	// Sub-column type. One of `json`, `hstore`. Required when `type` is `sub-column`, ignored otherwise.
	SubType pulumi.StringPtrInput
	// Object type. One of `db`, `schema`, `table`, `column`, `sub-column`.
	Type pulumi.StringInput
}

func (InventoryObjectArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*inventoryObjectArgs)(nil)).Elem()
}

type InventoryObjectInput interface {
	pulumi.Input

	ToInventoryObjectOutput() InventoryObjectOutput
	ToInventoryObjectOutputWithContext(ctx context.Context) InventoryObjectOutput
}

func (*InventoryObject) ElementType() reflect.Type {
	return reflect.TypeOf((**InventoryObject)(nil)).Elem()
}

func (i *InventoryObject) ToInventoryObjectOutput() InventoryObjectOutput {
	return i.ToInventoryObjectOutputWithContext(context.Background())
}

func (i *InventoryObject) ToInventoryObjectOutputWithContext(ctx context.Context) InventoryObjectOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InventoryObjectOutput)
}

// InventoryObjectArrayInput is an input type that accepts InventoryObjectArray and InventoryObjectArrayOutput values.
// You can construct a concrete instance of `InventoryObjectArrayInput` via:
//
//	InventoryObjectArray{ InventoryObjectArgs{...} }
type InventoryObjectArrayInput interface {
	pulumi.Input

	ToInventoryObjectArrayOutput() InventoryObjectArrayOutput
	ToInventoryObjectArrayOutputWithContext(context.Context) InventoryObjectArrayOutput
}

type InventoryObjectArray []InventoryObjectInput

func (InventoryObjectArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InventoryObject)(nil)).Elem()
}

func (i InventoryObjectArray) ToInventoryObjectArrayOutput() InventoryObjectArrayOutput {
	return i.ToInventoryObjectArrayOutputWithContext(context.Background())
}

func (i InventoryObjectArray) ToInventoryObjectArrayOutputWithContext(ctx context.Context) InventoryObjectArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InventoryObjectArrayOutput)
}

// InventoryObjectMapInput is an input type that accepts InventoryObjectMap and InventoryObjectMapOutput values.
// You can construct a concrete instance of `InventoryObjectMapInput` via:
//
//	InventoryObjectMap{ "key": InventoryObjectArgs{...} }
type InventoryObjectMapInput interface {
	pulumi.Input

	ToInventoryObjectMapOutput() InventoryObjectMapOutput
	ToInventoryObjectMapOutputWithContext(context.Context) InventoryObjectMapOutput
}

type InventoryObjectMap map[string]InventoryObjectInput

func (InventoryObjectMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InventoryObject)(nil)).Elem()
}

func (i InventoryObjectMap) ToInventoryObjectMapOutput() InventoryObjectMapOutput {
	return i.ToInventoryObjectMapOutputWithContext(context.Background())
}

func (i InventoryObjectMap) ToInventoryObjectMapOutputWithContext(ctx context.Context) InventoryObjectMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(InventoryObjectMapOutput)
}

type InventoryObjectOutput struct{ *pulumi.OutputState }

func (InventoryObjectOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**InventoryObject)(nil)).Elem()
}

func (o InventoryObjectOutput) ToInventoryObjectOutput() InventoryObjectOutput {
	return o
}

func (o InventoryObjectOutput) ToInventoryObjectOutputWithContext(ctx context.Context) InventoryObjectOutput {
	return o
}

// Column data type (e.g. `varchar`). Required when `type` is `column`, ignored otherwise.
func (o InventoryObjectOutput) DataType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InventoryObject) pulumi.StringPtrOutput { return v.DataType }).(pulumi.StringPtrOutput)
}

// Last segment of the path (e.g. `email`).
func (o InventoryObjectOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *InventoryObject) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Hierarchical path of the object (e.g. `mydb.public.users.email`).
func (o InventoryObjectOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *InventoryObject) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

// Resource (datastore) ID this object belongs to.
func (o InventoryObjectOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *InventoryObject) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

// Sub-column type. One of `json`, `hstore`. Required when `type` is `sub-column`, ignored otherwise.
func (o InventoryObjectOutput) SubType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *InventoryObject) pulumi.StringPtrOutput { return v.SubType }).(pulumi.StringPtrOutput)
}

// Object type. One of `db`, `schema`, `table`, `column`, `sub-column`.
func (o InventoryObjectOutput) Type() pulumi.StringOutput {
	return o.ApplyT(func(v *InventoryObject) pulumi.StringOutput { return v.Type }).(pulumi.StringOutput)
}

type InventoryObjectArrayOutput struct{ *pulumi.OutputState }

func (InventoryObjectArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*InventoryObject)(nil)).Elem()
}

func (o InventoryObjectArrayOutput) ToInventoryObjectArrayOutput() InventoryObjectArrayOutput {
	return o
}

func (o InventoryObjectArrayOutput) ToInventoryObjectArrayOutputWithContext(ctx context.Context) InventoryObjectArrayOutput {
	return o
}

func (o InventoryObjectArrayOutput) Index(i pulumi.IntInput) InventoryObjectOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *InventoryObject {
		return vs[0].([]*InventoryObject)[vs[1].(int)]
	}).(InventoryObjectOutput)
}

type InventoryObjectMapOutput struct{ *pulumi.OutputState }

func (InventoryObjectMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*InventoryObject)(nil)).Elem()
}

func (o InventoryObjectMapOutput) ToInventoryObjectMapOutput() InventoryObjectMapOutput {
	return o
}

func (o InventoryObjectMapOutput) ToInventoryObjectMapOutputWithContext(ctx context.Context) InventoryObjectMapOutput {
	return o
}

func (o InventoryObjectMapOutput) MapIndex(k pulumi.StringInput) InventoryObjectOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *InventoryObject {
		return vs[0].(map[string]*InventoryObject)[vs[1].(string)]
	}).(InventoryObjectOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*InventoryObjectInput)(nil)).Elem(), &InventoryObject{})
	pulumi.RegisterInputType(reflect.TypeOf((*InventoryObjectArrayInput)(nil)).Elem(), InventoryObjectArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*InventoryObjectMapInput)(nil)).Elem(), InventoryObjectMap{})
	pulumi.RegisterOutputType(InventoryObjectOutput{})
	pulumi.RegisterOutputType(InventoryObjectArrayOutput{})
	pulumi.RegisterOutputType(InventoryObjectMapOutput{})
}
