// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class ConnectorAiProviderAwsBedrockArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The AWS region.
        /// </summary>
        [Input("region", required: true)]
        public Input<string> Region { get; set; } = null!;

        public ConnectorAiProviderAwsBedrockArgs()
        {
        }
        public static new ConnectorAiProviderAwsBedrockArgs Empty => new ConnectorAiProviderAwsBedrockArgs();
    }
}
