// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class FormFieldConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("options")]
        private InputList<Inputs.FormFieldConfigOptionGetArgs>? _options;

        /// <summary>
        /// Static options for select-like fields.
        /// </summary>
        public InputList<Inputs.FormFieldConfigOptionGetArgs> Options
        {
            get => _options ?? (_options = new InputList<Inputs.FormFieldConfigOptionGetArgs>());
            set => _options = value;
        }

        /// <summary>
        /// Dynamic source used to fetch options.
        /// </summary>
        [Input("optionsSource")]
        public Input<Inputs.FormFieldConfigOptionsSourceGetArgs>? OptionsSource { get; set; }

        public FormFieldConfigGetArgs()
        {
        }
        public static new FormFieldConfigGetArgs Empty => new FormFieldConfigGetArgs();
    }
}
