// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class FormFieldConfigOptionsSourceCommandGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Command name.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public FormFieldConfigOptionsSourceCommandGetArgs()
        {
        }
        public static new FormFieldConfigOptionsSourceCommandGetArgs Empty => new FormFieldConfigOptionsSourceCommandGetArgs();
    }
}
