// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class IntegrationCloudAwsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows the Cloud Integration to access S3 buckets for Log Integrations.
        /// </summary>
        [Input("allowS3Access")]
        public Input<bool>? AllowS3Access { get; set; }

        /// <summary>
        /// The ARN of the IAM role that Formal assumes in your AWS account to access your resources.
        /// </summary>
        [Input("awsCustomerRoleArn")]
        public Input<string>? AwsCustomerRoleArn { get; set; }

        /// <summary>
        /// Enables resource autodiscovery for EC2 instances.
        /// </summary>
        [Input("enableEc2Autodiscovery")]
        public Input<bool>? EnableEc2Autodiscovery { get; set; }

        /// <summary>
        /// Enables resource autodiscovery for ECS clusters.
        /// </summary>
        [Input("enableEcsAutodiscovery")]
        public Input<bool>? EnableEcsAutodiscovery { get; set; }

        /// <summary>
        /// Enables resource autodiscovery for EKS clusters.
        /// </summary>
        [Input("enableEksAutodiscovery")]
        public Input<bool>? EnableEksAutodiscovery { get; set; }

        /// <summary>
        /// Enables resource autodiscovery for RDS instances (PostgreSQL, MySQL, MongoDB).
        /// </summary>
        [Input("enableRdsAutodiscovery")]
        public Input<bool>? EnableRdsAutodiscovery { get; set; }

        /// <summary>
        /// Enables resource autodiscovery for Redshift clusters.
        /// </summary>
        [Input("enableRedshiftAutodiscovery")]
        public Input<bool>? EnableRedshiftAutodiscovery { get; set; }

        /// <summary>
        /// Enables resource autodiscovery for S3 buckets.
        /// </summary>
        [Input("enableS3Autodiscovery")]
        public Input<bool>? EnableS3Autodiscovery { get; set; }

        /// <summary>
        /// The S3 bucket ARN this Cloud Integration is allowed to use for Log Integrations.
        /// </summary>
        [Input("s3BucketArn")]
        public Input<string>? S3BucketArn { get; set; }

        /// <summary>
        /// The template version of the CloudFormation stack. Use `latest` to stay in sync.
        /// </summary>
        [Input("templateVersion", required: true)]
        public Input<string> TemplateVersion { get; set; } = null!;

        public IntegrationCloudAwsArgs()
        {
        }
        public static new IntegrationCloudAwsArgs Empty => new IntegrationCloudAwsArgs();
    }
}
