// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class IntegrationMfaDuoArgs : global::Pulumi.ResourceArgs
    {
        [Input("apiHostname", required: true)]
        private Input<string>? _apiHostname;

        /// <summary>
        /// Duo API Hostname.
        /// </summary>
        public Input<string>? ApiHostname
        {
            get => _apiHostname;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _apiHostname = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Duo Integration Key.
        /// </summary>
        [Input("integrationKey", required: true)]
        public Input<string> IntegrationKey { get; set; } = null!;

        [Input("secretKey", required: true)]
        private Input<string>? _secretKey;

        /// <summary>
        /// Duo Secret Key.
        /// </summary>
        public Input<string>? SecretKey
        {
            get => _secretKey;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretKey = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public IntegrationMfaDuoArgs()
        {
        }
        public static new IntegrationMfaDuoArgs Empty => new IntegrationMfaDuoArgs();
    }
}
