// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class LogConfigurationStreamGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to encrypt stream data.
        /// </summary>
        [Input("encrypt", required: true)]
        public Input<bool> Encrypt { get; set; } = null!;

        public LogConfigurationStreamGetArgs()
        {
        }
        public static new LogConfigurationStreamGetArgs Empty => new LogConfigurationStreamGetArgs();
    }
}
