// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class LogConfigurationResponseGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to encrypt response payloads.
        /// </summary>
        [Input("encrypt", required: true)]
        public Input<bool> Encrypt { get; set; } = null!;

        /// <summary>
        /// Maximum size of response payloads to log.
        /// </summary>
        [Input("maxPayloadSize")]
        public Input<int>? MaxPayloadSize { get; set; }

        /// <summary>
        /// Duration to retain policy evaluation inputs for responses. Valid values: 1d, 2d, 3d, 7d, 14d, 21d, 30d.
        /// </summary>
        [Input("policyEvalInputRetention")]
        public Input<string>? PolicyEvalInputRetention { get; set; }

        public LogConfigurationResponseGetArgs()
        {
        }
        public static new LogConfigurationResponseGetArgs Empty => new LogConfigurationResponseGetArgs();
    }
}
