// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class LogConfigurationSessionGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Duration to retain policy evaluation inputs for sessions. Valid values: 1d, 2d, 3d, 7d, 14d, 21d, 30d.
        /// </summary>
        [Input("policyEvalInputRetention")]
        public Input<string>? PolicyEvalInputRetention { get; set; }

        public LogConfigurationSessionGetArgs()
        {
        }
        public static new LogConfigurationSessionGetArgs Empty => new LogConfigurationSessionGetArgs();
    }
}
