// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class NativeUserV3AwsIamGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The database username mapped to the IAM identity.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public NativeUserV3AwsIamGetArgs()
        {
        }
        public static new NativeUserV3AwsIamGetArgs Empty => new NativeUserV3AwsIamGetArgs();
    }
}
