// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class NativeUserV3HttpApiKeyHeaderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the header carrying the API key.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The API key. Set exactly one of `Literal`, `LiteralWo` or `EnvironmentVariable`.
        /// </summary>
        [Input("value", required: true)]
        public Input<Inputs.NativeUserV3HttpApiKeyHeaderValueArgs> Value { get; set; } = null!;

        public NativeUserV3HttpApiKeyHeaderArgs()
        {
        }
        public static new NativeUserV3HttpApiKeyHeaderArgs Empty => new NativeUserV3HttpApiKeyHeaderArgs();
    }
}
