// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class NativeUserV3AzureIamGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The database username mapped to the Azure identity.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public NativeUserV3AzureIamGetArgs()
        {
        }
        public static new NativeUserV3AzureIamGetArgs Empty => new NativeUserV3AzureIamGetArgs();
    }
}
