// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class NativeUserV3SnowflakeKeyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The private key. Set exactly one of `Literal`, `LiteralWo` or `EnvironmentVariable`.
        /// </summary>
        [Input("key", required: true)]
        public Input<Inputs.NativeUserV3SnowflakeKeyKeyGetArgs> Key { get; set; } = null!;

        /// <summary>
        /// The Snowflake username to authenticate as.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public NativeUserV3SnowflakeKeyGetArgs()
        {
        }
        public static new NativeUserV3SnowflakeKeyGetArgs Empty => new NativeUserV3SnowflakeKeyGetArgs();
    }
}
