// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class NativeUserV3HookGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("allowlistedEnvVariables")]
        private InputList<string>? _allowlistedEnvVariables;

        /// <summary>
        /// Environment variables the hook may read.
        /// </summary>
        public InputList<string> AllowlistedEnvVariables
        {
            get => _allowlistedEnvVariables ?? (_allowlistedEnvVariables = new InputList<string>());
            set => _allowlistedEnvVariables = value;
        }

        [Input("allowlistedNetworkHosts")]
        private InputList<string>? _allowlistedNetworkHosts;

        /// <summary>
        /// Network hosts the hook may access.
        /// </summary>
        public InputList<string> AllowlistedNetworkHosts
        {
            get => _allowlistedNetworkHosts ?? (_allowlistedNetworkHosts = new InputList<string>());
            set => _allowlistedNetworkHosts = value;
        }

        /// <summary>
        /// The TypeScript or JavaScript source of the hook, in the same form as `formal_hook.code`.
        /// </summary>
        [Input("code", required: true)]
        public Input<string> Code { get; set; } = null!;

        /// <summary>
        /// The credential shape the hook must return, so the connector can validate its result. One of: `Basic`, `AwsIam`, `AwsIamRole`, `GcpIam`, `AzureIam`, `KubernetesPath`, `KubernetesInline`, `SshKey`, `SnowflakeKey`, `HttpBasic`, `HttpBearer`, `HttpApiKeyHeader`, `HttpApiKeyQuery`.
        /// </summary>
        [Input("outputType", required: true)]
        public Input<string> OutputType { get; set; } = null!;

        public NativeUserV3HookGetArgs()
        {
        }
        public static new NativeUserV3HookGetArgs Empty => new NativeUserV3HookGetArgs();
    }
}
