// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Formal.Pulumi.Inputs
{

    public sealed class NativeUserV3KubernetesPathArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Path to the kubeconfig file on the connector. Set exactly one of `Literal`, `LiteralWo` or `EnvironmentVariable`.
        /// </summary>
        [Input("kubeconfigPath", required: true)]
        public Input<Inputs.NativeUserV3KubernetesPathKubeconfigPathArgs> KubeconfigPath { get; set; } = null!;

        public NativeUserV3KubernetesPathArgs()
        {
        }
        public static new NativeUserV3KubernetesPathArgs Empty => new NativeUserV3KubernetesPathArgs();
    }
}
