// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Registering a Connector Listener Rule with Formal.
 */
export class ConnectorListenerRule extends pulumi.CustomResource {
    /**
     * Get an existing ConnectorListenerRule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ConnectorListenerRuleState, opts?: pulumi.CustomResourceOptions): ConnectorListenerRule {
        return new ConnectorListenerRule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/connectorListenerRule:ConnectorListenerRule';

    /**
     * Returns true if the given object is an instance of ConnectorListenerRule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ConnectorListenerRule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ConnectorListenerRule.__pulumiType;
    }

    /**
     * The ID of the listener this rule is associated with.
     */
    declare public readonly connectorListenerId: pulumi.Output<string>;
    /**
     * The rule to apply to the listener. It should be either the id of the resource or the name of the technology.
     */
    declare public readonly rule: pulumi.Output<string>;
    /**
     * If set to true, this connector listener rule cannot be deleted.
     */
    declare public readonly terminationProtection: pulumi.Output<boolean | undefined>;
    /**
     * The type of the rule. It can be either `any`, `resource` or `technology`
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a ConnectorListenerRule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ConnectorListenerRuleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ConnectorListenerRuleArgs | ConnectorListenerRuleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ConnectorListenerRuleState | undefined;
            resourceInputs["connectorListenerId"] = state?.connectorListenerId;
            resourceInputs["rule"] = state?.rule;
            resourceInputs["terminationProtection"] = state?.terminationProtection;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as ConnectorListenerRuleArgs | undefined;
            if (args?.connectorListenerId === undefined && !opts.urn) {
                throw new Error("Missing required property 'connectorListenerId'");
            }
            if (args?.rule === undefined && !opts.urn) {
                throw new Error("Missing required property 'rule'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["connectorListenerId"] = args?.connectorListenerId;
            resourceInputs["rule"] = args?.rule;
            resourceInputs["terminationProtection"] = args?.terminationProtection;
            resourceInputs["type"] = args?.type;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ConnectorListenerRule.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ConnectorListenerRule resources.
 */
export interface ConnectorListenerRuleState {
    /**
     * The ID of the listener this rule is associated with.
     */
    connectorListenerId?: pulumi.Input<string | undefined>;
    /**
     * The rule to apply to the listener. It should be either the id of the resource or the name of the technology.
     */
    rule?: pulumi.Input<string | undefined>;
    /**
     * If set to true, this connector listener rule cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean | undefined>;
    /**
     * The type of the rule. It can be either `any`, `resource` or `technology`
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ConnectorListenerRule resource.
 */
export interface ConnectorListenerRuleArgs {
    /**
     * The ID of the listener this rule is associated with.
     */
    connectorListenerId: pulumi.Input<string>;
    /**
     * The rule to apply to the listener. It should be either the id of the resource or the name of the technology.
     */
    rule: pulumi.Input<string>;
    /**
     * If set to true, this connector listener rule cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean | undefined>;
    /**
     * The type of the rule. It can be either `any`, `resource` or `technology`
     */
    type: pulumi.Input<string>;
}
