// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Forms define reusable input schemas for workflows.
 */
export class Form extends pulumi.CustomResource {
    /**
     * Get an existing Form resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: FormState, opts?: pulumi.CustomResourceOptions): Form {
        return new Form(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/form:Form';

    /**
     * Returns true if the given object is an instance of Form.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Form {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Form.__pulumiType;
    }

    /**
     * When the form was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The form description.
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * List of fields that define the form schema.
     */
    declare public readonly fields: pulumi.Output<outputs.FormField[]>;
    /**
     * The name of the form. Must be unique within the organization.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Last update time.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a Form resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FormArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: FormArgs | FormState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as FormState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["description"] = state?.description;
            resourceInputs["fields"] = state?.fields;
            resourceInputs["name"] = state?.name;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as FormArgs | undefined;
            if (args?.fields === undefined && !opts.urn) {
                throw new Error("Missing required property 'fields'");
            }
            resourceInputs["description"] = args?.description;
            resourceInputs["fields"] = args?.fields;
            resourceInputs["name"] = args?.name;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Form.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Form resources.
 */
export interface FormState {
    /**
     * When the form was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * The form description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * List of fields that define the form schema.
     */
    fields?: pulumi.Input<pulumi.Input<inputs.FormField>[] | undefined>;
    /**
     * The name of the form. Must be unique within the organization.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Last update time.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Form resource.
 */
export interface FormArgs {
    /**
     * The form description.
     */
    description?: pulumi.Input<string | undefined>;
    /**
     * List of fields that define the form schema.
     */
    fields: pulumi.Input<pulumi.Input<inputs.FormField>[]>;
    /**
     * The name of the form. Must be unique within the organization.
     */
    name?: pulumi.Input<string | undefined>;
}
