// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Registering a Integration MDM app.
 */
export class IntegrationMdm extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationMdm resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationMdmState, opts?: pulumi.CustomResourceOptions): IntegrationMdm {
        return new IntegrationMdm(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/integrationMdm:IntegrationMdm';

    /**
     * Returns true if the given object is an instance of IntegrationMdm.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationMdm {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationMdm.__pulumiType;
    }

    /**
     * Configuration block for Kandji integration.
     */
    public readonly kandji!: pulumi.Output<outputs.IntegrationMdmKandji | undefined>;
    /**
     * Friendly name for the Integration app.
     */
    public readonly name!: pulumi.Output<string>;

    /**
     * Create a IntegrationMdm resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IntegrationMdmArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationMdmArgs | IntegrationMdmState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationMdmState | undefined;
            resourceInputs["kandji"] = state ? state.kandji : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
        } else {
            const args = argsOrState as IntegrationMdmArgs | undefined;
            resourceInputs["kandji"] = args ? args.kandji : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationMdm.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationMdm resources.
 */
export interface IntegrationMdmState {
    /**
     * Configuration block for Kandji integration.
     */
    kandji?: pulumi.Input<inputs.IntegrationMdmKandji>;
    /**
     * Friendly name for the Integration app.
     */
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a IntegrationMdm resource.
 */
export interface IntegrationMdmArgs {
    /**
     * Configuration block for Kandji integration.
     */
    kandji?: pulumi.Input<inputs.IntegrationMdmKandji>;
    /**
     * Friendly name for the Integration app.
     */
    name?: pulumi.Input<string>;
}
