// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Registering a Cloud integration.
 */
export class IntegrationCloud extends pulumi.CustomResource {
    /**
     * Get an existing IntegrationCloud resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: IntegrationCloudState, opts?: pulumi.CustomResourceOptions): IntegrationCloud {
        return new IntegrationCloud(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/integrationCloud:IntegrationCloud';

    /**
     * Returns true if the given object is an instance of IntegrationCloud.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is IntegrationCloud {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === IntegrationCloud.__pulumiType;
    }

    /**
     * Configuration block for AWS integration.
     */
    declare public readonly aws: pulumi.Output<outputs.IntegrationCloudAws | undefined>;
    /**
     * Whether AWS S3 access is allowed or not.
     */
    declare public /*out*/ readonly awsAllowS3Access: pulumi.Output<boolean>;
    /**
     * Whether AWS EC2 autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly awsEnableEc2Autodiscovery: pulumi.Output<boolean>;
    /**
     * Whether AWS ECS autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly awsEnableEcsAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether AWS EKS autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly awsEnableEksAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether AWS RDS autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly awsEnableRdsAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether AWS Redshift autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly awsEnableRedshiftAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether AWS S3 autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly awsEnableS3Autodiscovery: pulumi.Output<boolean>;
    /**
     * The IAM role ID Formal will use to access your resources.
     */
    declare public /*out*/ readonly awsFormalIamRole: pulumi.Output<string>;
    /**
     * The ARN of the IAM role Formal will use to access your resources.
     */
    declare public /*out*/ readonly awsFormalIamRoleArn: pulumi.Output<string>;
    /**
     * The SNS topic ARN CloudFormation can use to send events to Formal.
     */
    declare public /*out*/ readonly awsFormalPingbackArn: pulumi.Output<string>;
    /**
     * The AWS IAM role ARN Formal presents when federating into your GCP workload identity pool or your Entra tenant.
     */
    declare public /*out*/ readonly awsFormalRoleArn: pulumi.Output<string>;
    /**
     * A generated name for your CloudFormation stack.
     */
    declare public /*out*/ readonly awsFormalStackName: pulumi.Output<string>;
    /**
     * The AWS S3 bucket ARN this Cloud Integration is allowed to use for Log Integrations, if it is allowed to access S3.
     */
    declare public /*out*/ readonly awsS3BucketArn: pulumi.Output<string>;
    /**
     * The template body of the CloudFormation stack.
     */
    declare public /*out*/ readonly awsTemplateBody: pulumi.Output<string>;
    /**
     * Configuration block for Azure integration.
     */
    declare public readonly azure: pulumi.Output<outputs.IntegrationCloudAzure | undefined>;
    /**
     * Whether the Cloud Integration is allowed to write logs to Azure Blob Storage.
     */
    declare public /*out*/ readonly azureAllowBlobAccess: pulumi.Output<boolean>;
    /**
     * The storage accounts this Cloud Integration is allowed to write logs to.
     */
    declare public /*out*/ readonly azureBlobStorageAccounts: pulumi.Output<string[]>;
    /**
     * The client id of the managed identity Formal authenticates as, reported back by `formal.IntegrationCloudAzureActivation`.
     */
    declare public /*out*/ readonly azureClientId: pulumi.Output<string>;
    /**
     * Whether AKS cluster autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly azureEnableAksAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether Azure managed database server autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly azureEnableDbAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether Azure virtual machine autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly azureEnableVmAutodiscovery: pulumi.Output<boolean>;
    /**
     * The OIDC issuer URL of Formal's AWS account. Pass this to the Azure Terraform module, which pins it on the federated identity credential.
     */
    declare public /*out*/ readonly azureIssuer: pulumi.Output<string>;
    /**
     * The resource group discovery is narrowed to. Empty covers the whole subscription.
     */
    declare public /*out*/ readonly azureResourceGroup: pulumi.Output<string>;
    /**
     * The Azure built-in roles to grant Formal's managed identity, derived from the enabled capabilities. Pass these to the Azure Terraform module.
     */
    declare public /*out*/ readonly azureRoleDefinitions: pulumi.Output<string[]>;
    /**
     * The Azure subscription this integration grants Formal access to.
     */
    declare public /*out*/ readonly azureSubscriptionId: pulumi.Output<string>;
    /**
     * The Entra tenant of the managed identity Formal authenticates as, reported back by `formal.IntegrationCloudAzureActivation`.
     */
    declare public /*out*/ readonly azureTenantId: pulumi.Output<string>;
    /**
     * Region of the cloud provider. (AWS only)
     */
    declare public readonly cloudRegion: pulumi.Output<string | undefined>;
    /**
     * Configuration block for GCP integration.
     */
    declare public readonly gcp: pulumi.Output<outputs.IntegrationCloudGcp | undefined>;
    /**
     * Whether the Cloud Integration is allowed to write logs to GCS.
     */
    declare public /*out*/ readonly gcpAllowGcsAccess: pulumi.Output<boolean>;
    /**
     * Whether GCP Cloud SQL instances autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly gcpEnableCloudsqlInstancesAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether GCP Compute Engine instances autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly gcpEnableComputeInstancesAutodiscovery: pulumi.Output<boolean>;
    /**
     * Whether GCP GKE clusters autodiscovery is enabled or not.
     */
    declare public /*out*/ readonly gcpEnableGkeClustersAutodiscovery: pulumi.Output<boolean>;
    /**
     * The GCS buckets this Cloud Integration is allowed to write logs to. Empty with access allowed means all buckets in the project.
     */
    declare public /*out*/ readonly gcpGcsBuckets: pulumi.Output<string[]>;
    /**
     * The IAM permissions to grant Formal's service account, derived from the enabled capabilities. Pass these to the GCP Terraform module, which grants them through a single custom role.
     */
    declare public /*out*/ readonly gcpPermissions: pulumi.Output<string[]>;
    /**
     * The GCP project ID this integration grants Formal access to.
     */
    declare public /*out*/ readonly gcpProjectId: pulumi.Output<string>;
    /**
     * The project-level IAM roles to grant Formal's service account, derived from the enabled capabilities. Pass these to the GCP Terraform module.
     *
     * @deprecated Use gcp_permissions, which the GCP module grants through a single custom role.
     */
    declare public /*out*/ readonly gcpRoles: pulumi.Output<string[]>;
    /**
     * The GCP service account email created for this integration.
     */
    declare public /*out*/ readonly gcpServiceAccountEmail: pulumi.Output<string>;
    /**
     * The GCP workload identity pool provider created for this integration.
     */
    declare public /*out*/ readonly gcpWorkloadIdentityPoolProvider: pulumi.Output<string>;
    /**
     * Name of the Integration.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Type of the Integration. (Supported: aws, gcp)
     *
     * @deprecated This field is deprecated and will be removed in a future version.
     */
    declare public readonly type: pulumi.Output<string>;

    /**
     * Create a IntegrationCloud resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: IntegrationCloudArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: IntegrationCloudArgs | IntegrationCloudState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as IntegrationCloudState | undefined;
            resourceInputs["aws"] = state?.aws;
            resourceInputs["awsAllowS3Access"] = state?.awsAllowS3Access;
            resourceInputs["awsEnableEc2Autodiscovery"] = state?.awsEnableEc2Autodiscovery;
            resourceInputs["awsEnableEcsAutodiscovery"] = state?.awsEnableEcsAutodiscovery;
            resourceInputs["awsEnableEksAutodiscovery"] = state?.awsEnableEksAutodiscovery;
            resourceInputs["awsEnableRdsAutodiscovery"] = state?.awsEnableRdsAutodiscovery;
            resourceInputs["awsEnableRedshiftAutodiscovery"] = state?.awsEnableRedshiftAutodiscovery;
            resourceInputs["awsEnableS3Autodiscovery"] = state?.awsEnableS3Autodiscovery;
            resourceInputs["awsFormalIamRole"] = state?.awsFormalIamRole;
            resourceInputs["awsFormalIamRoleArn"] = state?.awsFormalIamRoleArn;
            resourceInputs["awsFormalPingbackArn"] = state?.awsFormalPingbackArn;
            resourceInputs["awsFormalRoleArn"] = state?.awsFormalRoleArn;
            resourceInputs["awsFormalStackName"] = state?.awsFormalStackName;
            resourceInputs["awsS3BucketArn"] = state?.awsS3BucketArn;
            resourceInputs["awsTemplateBody"] = state?.awsTemplateBody;
            resourceInputs["azure"] = state?.azure;
            resourceInputs["azureAllowBlobAccess"] = state?.azureAllowBlobAccess;
            resourceInputs["azureBlobStorageAccounts"] = state?.azureBlobStorageAccounts;
            resourceInputs["azureClientId"] = state?.azureClientId;
            resourceInputs["azureEnableAksAutodiscovery"] = state?.azureEnableAksAutodiscovery;
            resourceInputs["azureEnableDbAutodiscovery"] = state?.azureEnableDbAutodiscovery;
            resourceInputs["azureEnableVmAutodiscovery"] = state?.azureEnableVmAutodiscovery;
            resourceInputs["azureIssuer"] = state?.azureIssuer;
            resourceInputs["azureResourceGroup"] = state?.azureResourceGroup;
            resourceInputs["azureRoleDefinitions"] = state?.azureRoleDefinitions;
            resourceInputs["azureSubscriptionId"] = state?.azureSubscriptionId;
            resourceInputs["azureTenantId"] = state?.azureTenantId;
            resourceInputs["cloudRegion"] = state?.cloudRegion;
            resourceInputs["gcp"] = state?.gcp;
            resourceInputs["gcpAllowGcsAccess"] = state?.gcpAllowGcsAccess;
            resourceInputs["gcpEnableCloudsqlInstancesAutodiscovery"] = state?.gcpEnableCloudsqlInstancesAutodiscovery;
            resourceInputs["gcpEnableComputeInstancesAutodiscovery"] = state?.gcpEnableComputeInstancesAutodiscovery;
            resourceInputs["gcpEnableGkeClustersAutodiscovery"] = state?.gcpEnableGkeClustersAutodiscovery;
            resourceInputs["gcpGcsBuckets"] = state?.gcpGcsBuckets;
            resourceInputs["gcpPermissions"] = state?.gcpPermissions;
            resourceInputs["gcpProjectId"] = state?.gcpProjectId;
            resourceInputs["gcpRoles"] = state?.gcpRoles;
            resourceInputs["gcpServiceAccountEmail"] = state?.gcpServiceAccountEmail;
            resourceInputs["gcpWorkloadIdentityPoolProvider"] = state?.gcpWorkloadIdentityPoolProvider;
            resourceInputs["name"] = state?.name;
            resourceInputs["type"] = state?.type;
        } else {
            const args = argsOrState as IntegrationCloudArgs | undefined;
            resourceInputs["aws"] = args?.aws;
            resourceInputs["azure"] = args?.azure;
            resourceInputs["cloudRegion"] = args?.cloudRegion;
            resourceInputs["gcp"] = args?.gcp;
            resourceInputs["name"] = args?.name;
            resourceInputs["type"] = args?.type;
            resourceInputs["awsAllowS3Access"] = undefined /*out*/;
            resourceInputs["awsEnableEc2Autodiscovery"] = undefined /*out*/;
            resourceInputs["awsEnableEcsAutodiscovery"] = undefined /*out*/;
            resourceInputs["awsEnableEksAutodiscovery"] = undefined /*out*/;
            resourceInputs["awsEnableRdsAutodiscovery"] = undefined /*out*/;
            resourceInputs["awsEnableRedshiftAutodiscovery"] = undefined /*out*/;
            resourceInputs["awsEnableS3Autodiscovery"] = undefined /*out*/;
            resourceInputs["awsFormalIamRole"] = undefined /*out*/;
            resourceInputs["awsFormalIamRoleArn"] = undefined /*out*/;
            resourceInputs["awsFormalPingbackArn"] = undefined /*out*/;
            resourceInputs["awsFormalRoleArn"] = undefined /*out*/;
            resourceInputs["awsFormalStackName"] = undefined /*out*/;
            resourceInputs["awsS3BucketArn"] = undefined /*out*/;
            resourceInputs["awsTemplateBody"] = undefined /*out*/;
            resourceInputs["azureAllowBlobAccess"] = undefined /*out*/;
            resourceInputs["azureBlobStorageAccounts"] = undefined /*out*/;
            resourceInputs["azureClientId"] = undefined /*out*/;
            resourceInputs["azureEnableAksAutodiscovery"] = undefined /*out*/;
            resourceInputs["azureEnableDbAutodiscovery"] = undefined /*out*/;
            resourceInputs["azureEnableVmAutodiscovery"] = undefined /*out*/;
            resourceInputs["azureIssuer"] = undefined /*out*/;
            resourceInputs["azureResourceGroup"] = undefined /*out*/;
            resourceInputs["azureRoleDefinitions"] = undefined /*out*/;
            resourceInputs["azureSubscriptionId"] = undefined /*out*/;
            resourceInputs["azureTenantId"] = undefined /*out*/;
            resourceInputs["gcpAllowGcsAccess"] = undefined /*out*/;
            resourceInputs["gcpEnableCloudsqlInstancesAutodiscovery"] = undefined /*out*/;
            resourceInputs["gcpEnableComputeInstancesAutodiscovery"] = undefined /*out*/;
            resourceInputs["gcpEnableGkeClustersAutodiscovery"] = undefined /*out*/;
            resourceInputs["gcpGcsBuckets"] = undefined /*out*/;
            resourceInputs["gcpPermissions"] = undefined /*out*/;
            resourceInputs["gcpProjectId"] = undefined /*out*/;
            resourceInputs["gcpRoles"] = undefined /*out*/;
            resourceInputs["gcpServiceAccountEmail"] = undefined /*out*/;
            resourceInputs["gcpWorkloadIdentityPoolProvider"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(IntegrationCloud.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering IntegrationCloud resources.
 */
export interface IntegrationCloudState {
    /**
     * Configuration block for AWS integration.
     */
    aws?: pulumi.Input<inputs.IntegrationCloudAws | undefined>;
    /**
     * Whether AWS S3 access is allowed or not.
     */
    awsAllowS3Access?: pulumi.Input<boolean | undefined>;
    /**
     * Whether AWS EC2 autodiscovery is enabled or not.
     */
    awsEnableEc2Autodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether AWS ECS autodiscovery is enabled or not.
     */
    awsEnableEcsAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether AWS EKS autodiscovery is enabled or not.
     */
    awsEnableEksAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether AWS RDS autodiscovery is enabled or not.
     */
    awsEnableRdsAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether AWS Redshift autodiscovery is enabled or not.
     */
    awsEnableRedshiftAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether AWS S3 autodiscovery is enabled or not.
     */
    awsEnableS3Autodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * The IAM role ID Formal will use to access your resources.
     */
    awsFormalIamRole?: pulumi.Input<string | undefined>;
    /**
     * The ARN of the IAM role Formal will use to access your resources.
     */
    awsFormalIamRoleArn?: pulumi.Input<string | undefined>;
    /**
     * The SNS topic ARN CloudFormation can use to send events to Formal.
     */
    awsFormalPingbackArn?: pulumi.Input<string | undefined>;
    /**
     * The AWS IAM role ARN Formal presents when federating into your GCP workload identity pool or your Entra tenant.
     */
    awsFormalRoleArn?: pulumi.Input<string | undefined>;
    /**
     * A generated name for your CloudFormation stack.
     */
    awsFormalStackName?: pulumi.Input<string | undefined>;
    /**
     * The AWS S3 bucket ARN this Cloud Integration is allowed to use for Log Integrations, if it is allowed to access S3.
     */
    awsS3BucketArn?: pulumi.Input<string | undefined>;
    /**
     * The template body of the CloudFormation stack.
     */
    awsTemplateBody?: pulumi.Input<string | undefined>;
    /**
     * Configuration block for Azure integration.
     */
    azure?: pulumi.Input<inputs.IntegrationCloudAzure | undefined>;
    /**
     * Whether the Cloud Integration is allowed to write logs to Azure Blob Storage.
     */
    azureAllowBlobAccess?: pulumi.Input<boolean | undefined>;
    /**
     * The storage accounts this Cloud Integration is allowed to write logs to.
     */
    azureBlobStorageAccounts?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The client id of the managed identity Formal authenticates as, reported back by `formal.IntegrationCloudAzureActivation`.
     */
    azureClientId?: pulumi.Input<string | undefined>;
    /**
     * Whether AKS cluster autodiscovery is enabled or not.
     */
    azureEnableAksAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Azure managed database server autodiscovery is enabled or not.
     */
    azureEnableDbAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether Azure virtual machine autodiscovery is enabled or not.
     */
    azureEnableVmAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * The OIDC issuer URL of Formal's AWS account. Pass this to the Azure Terraform module, which pins it on the federated identity credential.
     */
    azureIssuer?: pulumi.Input<string | undefined>;
    /**
     * The resource group discovery is narrowed to. Empty covers the whole subscription.
     */
    azureResourceGroup?: pulumi.Input<string | undefined>;
    /**
     * The Azure built-in roles to grant Formal's managed identity, derived from the enabled capabilities. Pass these to the Azure Terraform module.
     */
    azureRoleDefinitions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The Azure subscription this integration grants Formal access to.
     */
    azureSubscriptionId?: pulumi.Input<string | undefined>;
    /**
     * The Entra tenant of the managed identity Formal authenticates as, reported back by `formal.IntegrationCloudAzureActivation`.
     */
    azureTenantId?: pulumi.Input<string | undefined>;
    /**
     * Region of the cloud provider. (AWS only)
     */
    cloudRegion?: pulumi.Input<string | undefined>;
    /**
     * Configuration block for GCP integration.
     */
    gcp?: pulumi.Input<inputs.IntegrationCloudGcp | undefined>;
    /**
     * Whether the Cloud Integration is allowed to write logs to GCS.
     */
    gcpAllowGcsAccess?: pulumi.Input<boolean | undefined>;
    /**
     * Whether GCP Cloud SQL instances autodiscovery is enabled or not.
     */
    gcpEnableCloudsqlInstancesAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether GCP Compute Engine instances autodiscovery is enabled or not.
     */
    gcpEnableComputeInstancesAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * Whether GCP GKE clusters autodiscovery is enabled or not.
     */
    gcpEnableGkeClustersAutodiscovery?: pulumi.Input<boolean | undefined>;
    /**
     * The GCS buckets this Cloud Integration is allowed to write logs to. Empty with access allowed means all buckets in the project.
     */
    gcpGcsBuckets?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The IAM permissions to grant Formal's service account, derived from the enabled capabilities. Pass these to the GCP Terraform module, which grants them through a single custom role.
     */
    gcpPermissions?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The GCP project ID this integration grants Formal access to.
     */
    gcpProjectId?: pulumi.Input<string | undefined>;
    /**
     * The project-level IAM roles to grant Formal's service account, derived from the enabled capabilities. Pass these to the GCP Terraform module.
     *
     * @deprecated Use gcp_permissions, which the GCP module grants through a single custom role.
     */
    gcpRoles?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * The GCP service account email created for this integration.
     */
    gcpServiceAccountEmail?: pulumi.Input<string | undefined>;
    /**
     * The GCP workload identity pool provider created for this integration.
     */
    gcpWorkloadIdentityPoolProvider?: pulumi.Input<string | undefined>;
    /**
     * Name of the Integration.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Type of the Integration. (Supported: aws, gcp)
     *
     * @deprecated This field is deprecated and will be removed in a future version.
     */
    type?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a IntegrationCloud resource.
 */
export interface IntegrationCloudArgs {
    /**
     * Configuration block for AWS integration.
     */
    aws?: pulumi.Input<inputs.IntegrationCloudAws | undefined>;
    /**
     * Configuration block for Azure integration.
     */
    azure?: pulumi.Input<inputs.IntegrationCloudAzure | undefined>;
    /**
     * Region of the cloud provider. (AWS only)
     */
    cloudRegion?: pulumi.Input<string | undefined>;
    /**
     * Configuration block for GCP integration.
     */
    gcp?: pulumi.Input<inputs.IntegrationCloudGcp | undefined>;
    /**
     * Name of the Integration.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Type of the Integration. (Supported: aws, gcp)
     *
     * @deprecated This field is deprecated and will be removed in a future version.
     */
    type?: pulumi.Input<string | undefined>;
}
