// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Creating a Health Check in Formal.
 */
export class ResourceHealthCheck extends pulumi.CustomResource {
    /**
     * Get an existing ResourceHealthCheck resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ResourceHealthCheckState, opts?: pulumi.CustomResourceOptions): ResourceHealthCheck {
        return new ResourceHealthCheck(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/resourceHealthCheck:ResourceHealthCheck';

    /**
     * Returns true if the given object is an instance of ResourceHealthCheck.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResourceHealthCheck {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ResourceHealthCheck.__pulumiType;
    }

    /**
     * Database associated with the health check.
     */
    declare public readonly databaseName: pulumi.Output<string>;
    /**
     * Resource ID linked to the following health check.
     */
    declare public readonly resourceId: pulumi.Output<string>;
    /**
     * If set to true, this Resource Health Check cannot be deleted.
     */
    declare public readonly terminationProtection: pulumi.Output<boolean | undefined>;

    /**
     * Create a ResourceHealthCheck resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceHealthCheckArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ResourceHealthCheckArgs | ResourceHealthCheckState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ResourceHealthCheckState | undefined;
            resourceInputs["databaseName"] = state?.databaseName;
            resourceInputs["resourceId"] = state?.resourceId;
            resourceInputs["terminationProtection"] = state?.terminationProtection;
        } else {
            const args = argsOrState as ResourceHealthCheckArgs | undefined;
            if (args?.databaseName === undefined && !opts.urn) {
                throw new Error("Missing required property 'databaseName'");
            }
            if (args?.resourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceId'");
            }
            resourceInputs["databaseName"] = args?.databaseName;
            resourceInputs["resourceId"] = args?.resourceId;
            resourceInputs["terminationProtection"] = args?.terminationProtection;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ResourceHealthCheck.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ResourceHealthCheck resources.
 */
export interface ResourceHealthCheckState {
    /**
     * Database associated with the health check.
     */
    databaseName?: pulumi.Input<string | undefined>;
    /**
     * Resource ID linked to the following health check.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * If set to true, this Resource Health Check cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a ResourceHealthCheck resource.
 */
export interface ResourceHealthCheckArgs {
    /**
     * Database associated with the health check.
     */
    databaseName: pulumi.Input<string>;
    /**
     * Resource ID linked to the following health check.
     */
    resourceId: pulumi.Input<string>;
    /**
     * If set to true, this Resource Health Check cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean | undefined>;
}
