// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Resource Classifier Configuration is a configuration for a resource classifier.
 */
export class ResourceClassifierConfiguration extends pulumi.CustomResource {
    /**
     * Get an existing ResourceClassifierConfiguration resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ResourceClassifierConfigurationState, opts?: pulumi.CustomResourceOptions): ResourceClassifierConfiguration {
        return new ResourceClassifierConfiguration(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/resourceClassifierConfiguration:ResourceClassifierConfiguration';

    /**
     * Returns true if the given object is an instance of ResourceClassifierConfiguration.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ResourceClassifierConfiguration {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ResourceClassifierConfiguration.__pulumiType;
    }

    /**
     * Which direction to apply AI analysis. Required. Supported values are `request` or `response`. Use preference=none to disable AI analysis entirely.
     */
    declare public readonly aiAnalysisScope: pulumi.Output<string>;
    /**
     * The timeout for the AI analysis in seconds.
     */
    declare public readonly aiAnalysisTimeoutSeconds: pulumi.Output<number>;
    /**
     * The timestamp of the Resource Classifier Preference creation.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * Whether to fail requests if the number of results from the classifier is not equal to the number of key-value pairs sent to it.
     */
    declare public readonly enforceStrictClassifierResultCount: pulumi.Output<boolean | undefined>;
    /**
     * The preference. Supported values are `nlp`, `llm`, `both`, and `none`.
     */
    declare public readonly preference: pulumi.Output<string>;
    /**
     * The ID of the Resource.
     */
    declare public readonly resourceId: pulumi.Output<string>;
    /**
     * The timestamp of the Resource Classifier Preference update.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<number>;

    /**
     * Create a ResourceClassifierConfiguration resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ResourceClassifierConfigurationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ResourceClassifierConfigurationArgs | ResourceClassifierConfigurationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ResourceClassifierConfigurationState | undefined;
            resourceInputs["aiAnalysisScope"] = state?.aiAnalysisScope;
            resourceInputs["aiAnalysisTimeoutSeconds"] = state?.aiAnalysisTimeoutSeconds;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["enforceStrictClassifierResultCount"] = state?.enforceStrictClassifierResultCount;
            resourceInputs["preference"] = state?.preference;
            resourceInputs["resourceId"] = state?.resourceId;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as ResourceClassifierConfigurationArgs | undefined;
            if (args?.aiAnalysisScope === undefined && !opts.urn) {
                throw new Error("Missing required property 'aiAnalysisScope'");
            }
            if (args?.aiAnalysisTimeoutSeconds === undefined && !opts.urn) {
                throw new Error("Missing required property 'aiAnalysisTimeoutSeconds'");
            }
            if (args?.preference === undefined && !opts.urn) {
                throw new Error("Missing required property 'preference'");
            }
            if (args?.resourceId === undefined && !opts.urn) {
                throw new Error("Missing required property 'resourceId'");
            }
            resourceInputs["aiAnalysisScope"] = args?.aiAnalysisScope;
            resourceInputs["aiAnalysisTimeoutSeconds"] = args?.aiAnalysisTimeoutSeconds;
            resourceInputs["enforceStrictClassifierResultCount"] = args?.enforceStrictClassifierResultCount;
            resourceInputs["preference"] = args?.preference;
            resourceInputs["resourceId"] = args?.resourceId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ResourceClassifierConfiguration.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering ResourceClassifierConfiguration resources.
 */
export interface ResourceClassifierConfigurationState {
    /**
     * Which direction to apply AI analysis. Required. Supported values are `request` or `response`. Use preference=none to disable AI analysis entirely.
     */
    aiAnalysisScope?: pulumi.Input<string | undefined>;
    /**
     * The timeout for the AI analysis in seconds.
     */
    aiAnalysisTimeoutSeconds?: pulumi.Input<number | undefined>;
    /**
     * The timestamp of the Resource Classifier Preference creation.
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * Whether to fail requests if the number of results from the classifier is not equal to the number of key-value pairs sent to it.
     */
    enforceStrictClassifierResultCount?: pulumi.Input<boolean | undefined>;
    /**
     * The preference. Supported values are `nlp`, `llm`, `both`, and `none`.
     */
    preference?: pulumi.Input<string | undefined>;
    /**
     * The ID of the Resource.
     */
    resourceId?: pulumi.Input<string | undefined>;
    /**
     * The timestamp of the Resource Classifier Preference update.
     */
    updatedAt?: pulumi.Input<number | undefined>;
}

/**
 * The set of arguments for constructing a ResourceClassifierConfiguration resource.
 */
export interface ResourceClassifierConfigurationArgs {
    /**
     * Which direction to apply AI analysis. Required. Supported values are `request` or `response`. Use preference=none to disable AI analysis entirely.
     */
    aiAnalysisScope: pulumi.Input<string>;
    /**
     * The timeout for the AI analysis in seconds.
     */
    aiAnalysisTimeoutSeconds: pulumi.Input<number>;
    /**
     * Whether to fail requests if the number of results from the classifier is not equal to the number of key-value pairs sent to it.
     */
    enforceStrictClassifierResultCount?: pulumi.Input<boolean | undefined>;
    /**
     * The preference. Supported values are `nlp`, `llm`, `both`, and `none`.
     */
    preference: pulumi.Input<string>;
    /**
     * The ID of the Resource.
     */
    resourceId: pulumi.Input<string>;
}
