// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Link a Satellite to another Satellite. For example, link a Data Discovery Satellite to an AI Satellite for column classification.
 */
export class SatelliteLink extends pulumi.CustomResource {
    /**
     * Get an existing SatelliteLink resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SatelliteLinkState, opts?: pulumi.CustomResourceOptions): SatelliteLink {
        return new SatelliteLink(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/satelliteLink:SatelliteLink';

    /**
     * Returns true if the given object is an instance of SatelliteLink.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SatelliteLink {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SatelliteLink.__pulumiType;
    }

    /**
     * The timestamp when the satellite link was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The ID of the source Satellite (e.g., Data Discovery Satellite).
     */
    declare public readonly sourceSatelliteId: pulumi.Output<string>;
    /**
     * The ID of the target Satellite (e.g., AI Satellite).
     */
    declare public readonly targetSatelliteId: pulumi.Output<string>;
    /**
     * The timestamp when the satellite link was last updated.
     */
    declare public /*out*/ readonly updatedAt: pulumi.Output<string>;

    /**
     * Create a SatelliteLink resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SatelliteLinkArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SatelliteLinkArgs | SatelliteLinkState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SatelliteLinkState | undefined;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["sourceSatelliteId"] = state?.sourceSatelliteId;
            resourceInputs["targetSatelliteId"] = state?.targetSatelliteId;
            resourceInputs["updatedAt"] = state?.updatedAt;
        } else {
            const args = argsOrState as SatelliteLinkArgs | undefined;
            if (args?.sourceSatelliteId === undefined && !opts.urn) {
                throw new Error("Missing required property 'sourceSatelliteId'");
            }
            if (args?.targetSatelliteId === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetSatelliteId'");
            }
            resourceInputs["sourceSatelliteId"] = args?.sourceSatelliteId;
            resourceInputs["targetSatelliteId"] = args?.targetSatelliteId;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SatelliteLink.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SatelliteLink resources.
 */
export interface SatelliteLinkState {
    /**
     * The timestamp when the satellite link was created.
     */
    createdAt?: pulumi.Input<string | undefined>;
    /**
     * The ID of the source Satellite (e.g., Data Discovery Satellite).
     */
    sourceSatelliteId?: pulumi.Input<string | undefined>;
    /**
     * The ID of the target Satellite (e.g., AI Satellite).
     */
    targetSatelliteId?: pulumi.Input<string | undefined>;
    /**
     * The timestamp when the satellite link was last updated.
     */
    updatedAt?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a SatelliteLink resource.
 */
export interface SatelliteLinkArgs {
    /**
     * The ID of the source Satellite (e.g., Data Discovery Satellite).
     */
    sourceSatelliteId: pulumi.Input<string>;
    /**
     * The ID of the target Satellite (e.g., AI Satellite).
     */
    targetSatelliteId: pulumi.Input<string>;
}
