// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Manage a Satellite Hostname.
 */
export class SatelliteHostname extends pulumi.CustomResource {
    /**
     * Get an existing SatelliteHostname resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SatelliteHostnameState, opts?: pulumi.CustomResourceOptions): SatelliteHostname {
        return new SatelliteHostname(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/satelliteHostname:SatelliteHostname';

    /**
     * Returns true if the given object is an instance of SatelliteHostname.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SatelliteHostname {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SatelliteHostname.__pulumiType;
    }

    /**
     * The timestamp when the satellite hostname was created.
     */
    public /*out*/ readonly createdAt!: pulumi.Output<string>;
    /**
     * The hostname for the satellite.
     */
    public readonly hostname!: pulumi.Output<string>;
    /**
     * The ID of the Satellite to create the hostname for.
     */
    public readonly satelliteId!: pulumi.Output<string>;
    /**
     * If set to true, this satellite hostname cannot be deleted.
     */
    public readonly terminationProtection!: pulumi.Output<boolean | undefined>;
    /**
     * The timestamp when the satellite hostname was last updated.
     */
    public /*out*/ readonly updatedAt!: pulumi.Output<string>;

    /**
     * Create a SatelliteHostname resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SatelliteHostnameArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SatelliteHostnameArgs | SatelliteHostnameState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SatelliteHostnameState | undefined;
            resourceInputs["createdAt"] = state ? state.createdAt : undefined;
            resourceInputs["hostname"] = state ? state.hostname : undefined;
            resourceInputs["satelliteId"] = state ? state.satelliteId : undefined;
            resourceInputs["terminationProtection"] = state ? state.terminationProtection : undefined;
            resourceInputs["updatedAt"] = state ? state.updatedAt : undefined;
        } else {
            const args = argsOrState as SatelliteHostnameArgs | undefined;
            if ((!args || args.hostname === undefined) && !opts.urn) {
                throw new Error("Missing required property 'hostname'");
            }
            if ((!args || args.satelliteId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'satelliteId'");
            }
            resourceInputs["hostname"] = args ? args.hostname : undefined;
            resourceInputs["satelliteId"] = args ? args.satelliteId : undefined;
            resourceInputs["terminationProtection"] = args ? args.terminationProtection : undefined;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["updatedAt"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SatelliteHostname.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering SatelliteHostname resources.
 */
export interface SatelliteHostnameState {
    /**
     * The timestamp when the satellite hostname was created.
     */
    createdAt?: pulumi.Input<string>;
    /**
     * The hostname for the satellite.
     */
    hostname?: pulumi.Input<string>;
    /**
     * The ID of the Satellite to create the hostname for.
     */
    satelliteId?: pulumi.Input<string>;
    /**
     * If set to true, this satellite hostname cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean>;
    /**
     * The timestamp when the satellite hostname was last updated.
     */
    updatedAt?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SatelliteHostname resource.
 */
export interface SatelliteHostnameArgs {
    /**
     * The hostname for the satellite.
     */
    hostname: pulumi.Input<string>;
    /**
     * The ID of the Satellite to create the hostname for.
     */
    satelliteId: pulumi.Input<string>;
    /**
     * If set to true, this satellite hostname cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean>;
}
