// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * (Deprecated) Registering a Sidecar with Formal.
 */
export class Sidecar extends pulumi.CustomResource {
    /**
     * Get an existing Sidecar resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SidecarState, opts?: pulumi.CustomResourceOptions): Sidecar {
        return new Sidecar(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'formal:index/sidecar:Sidecar';

    /**
     * Returns true if the given object is an instance of Sidecar.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Sidecar {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Sidecar.__pulumiType;
    }

    /**
     * Api key for the deployed Sidecar.
     */
    declare public /*out*/ readonly apiKey: pulumi.Output<string>;
    /**
     * Creation time of the sidecar.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<number>;
    /**
     * If deploymentType is onprem, this is the Control Plane TLS Certificate to add to the deployed Sidecar.
     */
    declare public /*out*/ readonly formalControlPlaneTlsCertificate: pulumi.Output<string>;
    /**
     * The hostname of the created sidecar.
     */
    declare public readonly hostname: pulumi.Output<string>;
    /**
     * Friendly name for this Sidecar.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Technology of the Datastore: supported values are `snowflake`, `postgres`, `redshift`, `mysql`, `mariadb`, `s3`, `dynamodb`, `mongodb`, `documentdb`, `http`, `ssh`, `aws`, and `gcp`.
     */
    declare public readonly technology: pulumi.Output<string>;
    /**
     * If set to true, this Sidecar cannot be deleted.
     */
    declare public readonly terminationProtection: pulumi.Output<boolean | undefined>;
    /**
     * Version of the Sidecar to deploy for `managed`.
     */
    declare public readonly version: pulumi.Output<string | undefined>;

    /**
     * Create a Sidecar resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SidecarArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SidecarArgs | SidecarState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SidecarState | undefined;
            resourceInputs["apiKey"] = state?.apiKey;
            resourceInputs["createdAt"] = state?.createdAt;
            resourceInputs["formalControlPlaneTlsCertificate"] = state?.formalControlPlaneTlsCertificate;
            resourceInputs["hostname"] = state?.hostname;
            resourceInputs["name"] = state?.name;
            resourceInputs["technology"] = state?.technology;
            resourceInputs["terminationProtection"] = state?.terminationProtection;
            resourceInputs["version"] = state?.version;
        } else {
            const args = argsOrState as SidecarArgs | undefined;
            if (args?.hostname === undefined && !opts.urn) {
                throw new Error("Missing required property 'hostname'");
            }
            if (args?.technology === undefined && !opts.urn) {
                throw new Error("Missing required property 'technology'");
            }
            resourceInputs["hostname"] = args?.hostname;
            resourceInputs["name"] = args?.name;
            resourceInputs["technology"] = args?.technology;
            resourceInputs["terminationProtection"] = args?.terminationProtection;
            resourceInputs["version"] = args?.version;
            resourceInputs["apiKey"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["formalControlPlaneTlsCertificate"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["apiKey", "formalControlPlaneTlsCertificate"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Sidecar.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Sidecar resources.
 */
export interface SidecarState {
    /**
     * Api key for the deployed Sidecar.
     */
    apiKey?: pulumi.Input<string | undefined>;
    /**
     * Creation time of the sidecar.
     */
    createdAt?: pulumi.Input<number | undefined>;
    /**
     * If deploymentType is onprem, this is the Control Plane TLS Certificate to add to the deployed Sidecar.
     */
    formalControlPlaneTlsCertificate?: pulumi.Input<string | undefined>;
    /**
     * The hostname of the created sidecar.
     */
    hostname?: pulumi.Input<string | undefined>;
    /**
     * Friendly name for this Sidecar.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Technology of the Datastore: supported values are `snowflake`, `postgres`, `redshift`, `mysql`, `mariadb`, `s3`, `dynamodb`, `mongodb`, `documentdb`, `http`, `ssh`, `aws`, and `gcp`.
     */
    technology?: pulumi.Input<string | undefined>;
    /**
     * If set to true, this Sidecar cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean | undefined>;
    /**
     * Version of the Sidecar to deploy for `managed`.
     */
    version?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a Sidecar resource.
 */
export interface SidecarArgs {
    /**
     * The hostname of the created sidecar.
     */
    hostname: pulumi.Input<string>;
    /**
     * Friendly name for this Sidecar.
     */
    name?: pulumi.Input<string | undefined>;
    /**
     * Technology of the Datastore: supported values are `snowflake`, `postgres`, `redshift`, `mysql`, `mariadb`, `s3`, `dynamodb`, `mongodb`, `documentdb`, `http`, `ssh`, `aws`, and `gcp`.
     */
    technology: pulumi.Input<string>;
    /**
     * If set to true, this Sidecar cannot be deleted.
     */
    terminationProtection?: pulumi.Input<boolean | undefined>;
    /**
     * Version of the Sidecar to deploy for `managed`.
     */
    version?: pulumi.Input<string | undefined>;
}
